<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $districts =
            [
                ["code" => "9000" , "province_id" => "1", "district_en"=> "(Capital) Kabul", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "1", "district_en"=> "CHAHAR ASYAB", "district_dr"=> "چهارآسیاب", "district_ps" => "چهارآسیاب"],
                ["code" => "" , "province_id" => "1", "district_en"=> "BAGRAMI", "district_dr"=> "بگرامی", "district_ps" => "بگرامی"],
                ["code" => "" , "province_id" => "1", "district_en"=> "DEHSABZ", "district_dr"=> "ده سبز", "district_ps" => "ده سبز"],
                ["code" => "" , "province_id" => "1", "district_en"=> "SHAKAR DARA", "district_dr"=> "شکردره", "district_ps" => "شکردره"],
                ["code" => "" , "province_id" => "1", "district_en"=> "MUSAHI", "district_dr"=> "موسئی", "district_ps" => "موسئی"],
                ["code" => "" , "province_id" => "1", "district_en"=> "MIR BACHA KOT", "district_dr"=> "میر بچه کوت", "district_ps" => "میر بچه کوت"],
                ["code" => "" , "province_id" => "1", "district_en"=> "KHAK-E-JABAR", "district_dr"=> "خاک جبار", "district_ps" => "خاک جبار"],
                ["code" => "" , "province_id" => "1", "district_en"=> "KALAKAN", "district_dr"=> "کلکان", "district_ps" => "کلکان"],
                ["code" => "" , "province_id" => "1", "district_en"=> "GULDARA", "district_dr"=> "گلدره", "district_ps" => "گلدره"],
                ["code" => "" , "province_id" => "1", "district_en"=> "FARZA", "district_dr"=> "فرزه", "district_ps" => "فرزه"],
                ["code" => "" , "province_id" => "1", "district_en"=> "ESTALEF", "district_dr"=> "استالف", "district_ps" => "استالف"],
                ["code" => "" , "province_id" => "1", "district_en"=> "QARA BAGH", "district_dr"=> "قره باغ", "district_ps" => "قره باغ"],
                ["code" => "" , "province_id" => "1", "district_en"=> "SURUBI", "district_dr"=> "سروبی", "district_ps" => "سروبی"],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD1", "district_dr"=> "ناحیه1", "district_ps" => "ناحیه1"],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD2", "district_dr"=> "ناحیه2", "district_ps" => "ناحیه2"],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD3", "district_dr"=> "ناحیه3", "district_ps" => "ناحیه3"],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 5", "district_dr"=> "ناحیه 5", "district_ps" => "ناحیه 5"],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 6 ", "district_dr"=> "ناحیه 6 ", "district_ps" => "ناحیه 6 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 7 ", "district_dr"=> "ناحیه 7 ", "district_ps" => "ناحیه 7 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 8 ", "district_dr"=> "ناحیه 8 ", "district_ps" => "ناحیه 8 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 9 ", "district_dr"=> "ناحیه 9 ", "district_ps" => "ناحیه 9 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 10 ", "district_dr"=> "ناحیه 10 ", "district_ps" => "ناحیه 10 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 11 ", "district_dr"=> "ناحیه 11 ", "district_ps" => "ناحیه 11 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 12 ", "district_dr"=> "ناحیه 12 ", "district_ps" => "ناحیه 12 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 13 ", "district_dr"=> "ناحیه 13 ", "district_ps" => "ناحیه 13 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 14 ", "district_dr"=> "ناحیه 14 ", "district_ps" => "ناحیه 14 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 15 ", "district_dr"=> "ناحیه 15 ", "district_ps" => "ناحیه 15 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 16 ", "district_dr"=> "ناحیه 16 ", "district_ps" => "ناحیه 16 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 17 ", "district_dr"=> "ناحیه 17 ", "district_ps" => "ناحیه 17 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 18 ", "district_dr"=> "ناحیه 18 ", "district_ps" => "ناحیه 18 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 19 ", "district_dr"=> "ناحیه 19 ", "district_ps" => "ناحیه 19 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 20 ", "district_dr"=> "ناحیه 20 ", "district_ps" => "ناحیه 20 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 21 ", "district_dr"=> "ناحیه 21 ", "district_ps" => "ناحیه 21 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "PD 22 ", "district_dr"=> "ناحیه 22 ", "district_ps" => "ناحیه 22 "],
                ["code" => "" , "province_id" => "1", "district_en"=> "Paghman", "district_dr"=> "پغمان", "district_ps" => "پغمان"],
                ["code" => "" , "province_id" => "1", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "2", "district_en"=> "(Capital) MAHMUDI RAQI", "district_dr"=> "مرکز(محمود راقی)", "district_ps" => "مرکز(محمود راقی)"],
                ["code" => "" , "province_id" => "2", "district_en"=> "HISSA-E- DUWUMI KOHISTAN", "district_dr"=> "حصه دوم کوهستان", "district_ps" => "حصه دوم کوهستان"],
                ["code" => "" , "province_id" => "2", "district_en"=> "KOH BAND", "district_dr"=> "کوه بند", "district_ps" => "کوه بند"],
                ["code" => "" , "province_id" => "2", "district_en"=> "HISSA-E-AWALI KOHISTAN", "district_dr"=> "حصه اول کوهستان", "district_ps" => "حصه اول کوهستان"],
                ["code" => "" , "province_id" => "2", "district_en"=> "NIJRAB", "district_dr"=> "نجراب", "district_ps" => "نجراب"],
                ["code" => "" , "province_id" => "2", "district_en"=> "TAGAB", "district_dr"=> "تگاب", "district_ps" => "تگاب"],
                ["code" => "" , "province_id" => "2", "district_en"=> "ALASAY", "district_dr"=> "اله سای", "district_ps" => "اله سای"],
                ["code" => "" , "province_id" => "2", "district_en"=> "Unknown", "district_dr"=> "نا معلوم", "district_ps" => "نا معلوم"],
                ["code" => "" , "province_id" => "2", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "2", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "2", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "3", "district_en"=> "(Capital) CHARIKAR", "district_dr"=> "مرکز(چاریکار)", "district_ps" => "مرکز(چاریکار)"],
                ["code" => "" , "province_id" => "3", "district_en"=> "BAGRAM", "district_dr"=> "بگرام", "district_ps" => "بگرام"],
                ["code" => "" , "province_id" => "3", "district_en"=> "SHINWARI", "district_dr"=> "شینواری", "district_ps" => "شینواری"],
                ["code" => "" , "province_id" => "3", "district_en"=> "SAYID KHALE", "district_dr"=> "سید خیل", "district_ps" => "سید خیل"],
                ["code" => "" , "province_id" => "3", "district_en"=> "JABULUSSARAJ", "district_dr"=> "جبل السراج", "district_ps" => "جبل السراج"],
                ["code" => "" , "province_id" => "3", "district_en"=> "SALANG", "district_dr"=> "سالنگ", "district_ps" => "سالنگ"],
                ["code" => "" , "province_id" => "3", "district_en"=> "SYAHGIRDI GHORBAND", "district_dr"=> "سیاه گرد غوربند", "district_ps" => "سیاه گرد غوربند"],
                ["code" => "" , "province_id" => "3", "district_en"=> "KOHI SAFI", "district_dr"=> "کوه صافی", "district_ps" => "کوه صافی"],
                ["code" => "" , "province_id" => "3", "district_en"=> "SORKHI PARSA", "district_dr"=> "سرخ پارسا", "district_ps" => "سرخ پارسا"],
                ["code" => "" , "province_id" => "3", "district_en"=> "SHAYKH ALI", "district_dr"=> "شیخ علی", "district_ps" => "شیخ علی"],
                ["code" => "" , "province_id" => "3", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "3", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "3", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "3", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "3", "district_en"=> "PD 5", "district_dr"=> "ناحیه 5", "district_ps" => "ناحیه 5"],
                ["code" => "" , "province_id" => "3", "district_en"=> "PD 6", "district_dr"=> "ناحیه 6", "district_ps" => "ناحیه 6"],
                ["code" => "" , "province_id" => "3", "district_en"=> "PD 7", "district_dr"=> "ناحیه 7", "district_ps" => "ناحیه 7"],
                ["code" => "" , "province_id" => "3", "district_en"=> "GUL BAHAR", "district_dr"=> "گلبهار", "district_ps" => "گلبهار"],
                ["code" => "" , "province_id" => "3", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "4", "district_en"=> "(Capital) MAYDAN SHAHR", "district_dr"=> "مرکز(میدان شهر)", "district_ps" => "مرکز(میدان شهر)"],
                ["code" => "" , "province_id" => "4", "district_en"=> "NERKH", "district_dr"=> "نرخ", "district_ps" => "نرخ"],
                ["code" => "" , "province_id" => "4", "district_en"=> "JALREZ", "district_dr"=> "جلریز", "district_ps" => "جلریز"],
                ["code" => "" , "province_id" => "4", "district_en"=> "CHAKI WARDAK", "district_dr"=> "چک وردک", "district_ps" => "چک وردک"],
                ["code" => "" , "province_id" => "4", "district_en"=> "SAYYDABAD", "district_dr"=> "سید آباد", "district_ps" => "سید آباد"],
                ["code" => "" , "province_id" => "4", "district_en"=> "DAYMIRDAD", "district_dr"=> "دایمیرداد", "district_ps" => "دایمیرداد"],
                ["code" => "" , "province_id" => "4", "district_en"=> "HISSA-E-AWALI BIHSUD", "district_dr"=> "حصه اول بهسود", "district_ps" => "حصه اول بهسود"],
                ["code" => "" , "province_id" => "4", "district_en"=> "JAGHATU", "district_dr"=> "جغتو", "district_ps" => "جغتو"],
                ["code" => "" , "province_id" => "4", "district_en"=> "MARKAZ-E-BEHSUD", "district_dr"=> "مرکز بهسود", "district_ps" => "مرکز بهسود"],
                ["code" => "" , "province_id" => "4", "district_en"=> "HESE DOWM BEHSOOD", "district_dr"=> "حصه دوم بهسود", "district_ps" => "حصه دوم بهسود"],
                ["code" => "" , "province_id" => "4", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "5", "district_en"=> "(Capital) PULI ALAM", "district_dr"=> "مرکز(پل علم)", "district_ps" => "مرکز(پل علم)"],
                ["code" => "" , "province_id" => "5", "district_en"=> "BARAKI BARAK", "district_dr"=> "برکی برک", "district_ps" => "برکی برک"],
                ["code" => "" , "province_id" => "5", "district_en"=> "CHARKH", "district_dr"=> "چرخ", "district_ps" => "چرخ"],
                ["code" => "" , "province_id" => "5", "district_en"=> "KHUSHI", "district_dr"=> "خوشی", "district_ps" => "خوشی"],
                ["code" => "" , "province_id" => "5", "district_en"=> "MOHAMMAD AGHA", "district_dr"=> "محمد آغه", "district_ps" => "محمد آغه"],
                ["code" => "" , "province_id" => "5", "district_en"=> "KHAR WAR", "district_dr"=> "خروار", "district_ps" => "خروار"],
                ["code" => "" , "province_id" => "5", "district_en"=> "AZRA", "district_dr"=> "ازره", "district_ps" => "ازره"],
                ["code" => "" , "province_id" => "5", "district_en"=> "Unknown", "district_dr"=> "نا معلوم", "district_ps" => "نا معلوم"],
                ["code" => "" , "province_id" => "6", "district_en"=> "(Capital) Jalalabad", "district_dr"=> "مرکز(جلال آباد)", "district_ps" => "مرکز(جلال آباد)"],
                ["code" => "" , "province_id" => "6", "district_en"=> "BEHSUD", "district_dr"=> "بهسود", "district_ps" => "بهسود"],
                ["code" => "" , "province_id" => "6", "district_en"=> "SORKH RUD", "district_dr"=> "سرخرود", "district_ps" => "سرخرود"],
                ["code" => "" , "province_id" => "6", "district_en"=> "CHAPARHAR", "district_dr"=> "چپرهار", "district_ps" => "چپرهار"],
                ["code" => "" , "province_id" => "6", "district_en"=> "KAMA", "district_dr"=> "کامه", "district_ps" => "کامه"],
                ["code" => "" , "province_id" => "6", "district_en"=> "KUZKUNAR", "district_dr"=> "کوزکنر", "district_ps" => "کوزکنر"],
                ["code" => "" , "province_id" => "6", "district_en"=> "RODAT", "district_dr"=> "رودات", "district_ps" => "رودات"],
                ["code" => "" , "province_id" => "6", "district_en"=> "KHUGYANI", "district_dr"=> "خوگیانی", "district_ps" => "خوگیانی"],
                ["code" => "" , "province_id" => "6", "district_en"=> "BATI KOT", "district_dr"=> "بتی کوت", "district_ps" => "بتی کوت"],
                ["code" => "" , "province_id" => "6", "district_en"=> "DEH BALA", "district_dr"=> "ده بالا", "district_ps" => "ده بالا"],
                ["code" => "" , "province_id" => "6", "district_en"=> "PACHIR WAGAM", "district_dr"=> "پچیرواگام", "district_ps" => "پچیرواگام"],
                ["code" => "" , "province_id" => "6", "district_en"=> "DARAH-E-NOOR", "district_dr"=> "دره نور", "district_ps" => "دره نور"],
                ["code" => "" , "province_id" => "6", "district_en"=> "KOT", "district_dr"=> "کوت", "district_ps" => "کوت"],
                ["code" => "" , "province_id" => "6", "district_en"=> "GOSHTA", "district_dr"=> "گوشته", "district_ps" => "گوشته"],
                ["code" => "" , "province_id" => "6", "district_en"=> "ACHIN", "district_dr"=> "اچین", "district_ps" => "اچین"],
                ["code" => "" , "province_id" => "6", "district_en"=> "SHINWAR", "district_dr"=> "شینوار", "district_ps" => "شینوار"],
                ["code" => "" , "province_id" => "6", "district_en"=> "MUHMAND DARA", "district_dr"=> "مهمنددره", "district_ps" => "مهمنددره"],
                ["code" => "" , "province_id" => "6", "district_en"=> "LALPOOR", "district_dr"=> "لعل پور", "district_ps" => "لعل پور"],
                ["code" => "" , "province_id" => "6", "district_en"=> "SHER ZAD", "district_dr"=> "شیرزاد", "district_ps" => "شیرزاد"],
                ["code" => "" , "province_id" => "6", "district_en"=> "NAZYAN", "district_dr"=> "نازیان", "district_ps" => "نازیان"],
                ["code" => "" , "province_id" => "6", "district_en"=> "HESARAK", "district_dr"=> "حصارک", "district_ps" => "حصارک"],
                ["code" => "" , "province_id" => "6", "district_en"=> "DUR BABA", "district_dr"=> "دربابا", "district_ps" => "دربابا"],
                ["code" => "" , "province_id" => "6", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "6", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "6", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "6", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "6", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "6", "district_en"=> "PD 5", "district_dr"=> "ناحیه 5", "district_ps" => "ناحیه 5"],
                ["code" => "" , "province_id" => "6", "district_en"=> "Haska Meena", "district_dr"=> "هسکه مینه ", "district_ps" => "هسکه مینه "],
                ["code" => "" , "province_id" => "6", "district_en"=> "SPENGHAR", "district_dr"=> "اسپین غر ", "district_ps" => "اسپین غر "],
                ["code" => "" , "province_id" => "6", "district_en"=> "TORKHAM", "district_dr"=> "تورخم ", "district_ps" => " تورخم "],
                ["code" => "" , "province_id" => "6", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "7", "district_en"=> "(Capital) MEHTERLAM", "district_dr"=> "مرکز(مهترلام)", "district_ps" => "مرکز(مهترلام)"],
                ["code" => "" , "province_id" => "7", "district_en"=> "QARGHAYEE", "district_dr"=> "قرغیی", "district_ps" => "قرغیی"],
                ["code" => "" , "province_id" => "7", "district_en"=> "ALISHING", "district_dr"=> "علیشنگ", "district_ps" => "علیشنگ"],
                ["code" => "" , "province_id" => "7", "district_en"=> "ALINGAR", "district_dr"=> "علینگار", "district_ps" => "علینگار"],
                ["code" => "" , "province_id" => "7", "district_en"=> "DAWLAT SHAH", "district_dr"=> "دولت شاه", "district_ps" => "دولت شاه"],
                ["code" => "" , "province_id" => "7", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "7", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "7", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "7", "district_en"=> "Laghman University ", "district_dr"=> "پوهنتون لغمان", "district_ps" => "پوهنتون لغمان"],
                ["code" => "" , "province_id" => "7", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "8", "district_en"=> "(Capital) BAZARAK", "district_dr"=> "مرکز(بازارک)", "district_ps" => "مرکز(بازارک)"],
                ["code" => "" , "province_id" => "8", "district_en"=> "RUKHA", "district_dr"=> "رخه", "district_ps" => "رخه"],
                ["code" => "" , "province_id" => "8", "district_en"=> "DARAH", "district_dr"=> "دره", "district_ps" => "دره"],
                ["code" => "" , "province_id" => "8", "district_en"=> "HISSA-E-AWAL ( KHINJ )", "district_dr"=> "حصه اول - خنج", "district_ps" => "حصه اول - خنج"],
                ["code" => "" , "province_id" => "8", "district_en"=> "UNABA", "district_dr"=> "عنابه", "district_ps" => "عنابه"],
                ["code" => "" , "province_id" => "8", "district_en"=> "SHUTUL", "district_dr"=> "شتل", "district_ps" => "شتل"],
                ["code" => "" , "province_id" => "8", "district_en"=> "PARYAN", "district_dr"=> "پریان", "district_ps" => "پریان"],
                ["code" => "" , "province_id" => "8", "district_en"=> "ABSHAR", "district_dr"=> "آبشار", "district_ps" => "آبشار"],
                ["code" => "" , "province_id" => "8", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "9", "district_en"=> "(Capital) PUL-E-KHUMRI", "district_dr"=> "مرکز(پلخمری)", "district_ps" => "مرکز(پلخمری)"],
                ["code" => "" , "province_id" => "9", "district_en"=> "DAHANA-E-GHURI", "district_dr"=> "دهنه غوری", "district_ps" => "دهنه غوری"],
                ["code" => "" , "province_id" => "9", "district_en"=> "DUSHI", "district_dr"=> "دوشی", "district_ps" => "دوشی"],
                ["code" => "" , "province_id" => "9", "district_en"=> "NAHREEN", "district_dr"=> "نهرین", "district_ps" => "نهرین"],
                ["code" => "" , "province_id" => "9", "district_en"=> "BAGHLAN-E-JADEED", "district_dr"=> "بغلان جید", "district_ps" => "بغلان جید"],
                ["code" => "" , "province_id" => "9", "district_en"=> "KHINJAN", "district_dr"=> "خنجان", "district_ps" => "خنجان"],
                ["code" => "" , "province_id" => "9", "district_en"=> "ANDARAB", "district_dr"=> "اندراب", "district_ps" => "اندراب"],
                ["code" => "" , "province_id" => "9", "district_en"=> "DEH SALAH", "district_dr"=> "ده صلاح", "district_ps" => "ده صلاح"],
                ["code" => "" , "province_id" => "9", "district_en"=> "JALGA", "district_dr"=> "جلگه", "district_ps" => "جلگه"],
                ["code" => "" , "province_id" => "9", "district_en"=> "BURKA", "district_dr"=> "برکه", "district_ps" => "برکه"],
                ["code" => "" , "province_id" => "9", "district_en"=> "TALA WA BARFAK", "district_dr"=> "تاله وبرفک", "district_ps" => "تاله وبرفک"],
                ["code" => "" , "province_id" => "9", "district_en"=> "PUL-E-HISAR", "district_dr"=> "پل حصار", "district_ps" => "پل حصار"],
                ["code" => "" , "province_id" => "9", "district_en"=> "KHOST WA FIRING", "district_dr"=> "خوست و فرنگ", "district_ps" => "خوست و فرنگ"],
                ["code" => "" , "province_id" => "9", "district_en"=> "GOZARGAH-E-NOOR", "district_dr"=> "گذرگاه نور", "district_ps" => "گذرگاه نور"],
                ["code" => "" , "province_id" => "9", "district_en"=> "FIRING WA GHARU", "district_dr"=> "فرنگ وغارو", "district_ps" => "فرنگ وغارو"],
                ["code" => "" , "province_id" => "9", "district_en"=> "PD 1 ", "district_dr"=> "ناحیه 1 ", "district_ps" => "ناحیه 1 "],
                ["code" => "" , "province_id" => "9", "district_en"=> "PD 2 ", "district_dr"=> "ناحیه 2 ", "district_ps" => "ناحیه 2 "],
                ["code" => "" , "province_id" => "9", "district_en"=> "PD 3 ", "district_dr"=> "ناحیه 3 ", "district_ps" => "ناحیه 3 "],
                ["code" => "" , "province_id" => "9", "district_en"=> "PD 4 ", "district_dr"=> "ناحیه 4 ", "district_ps" => "ناحیه 4 "],
                ["code" => "" , "province_id" => "9", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "10", "district_en"=> "(Capital) BAMYAN", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "10", "district_en"=> "SHEBAR", "district_dr"=> "شیبر", "district_ps" => "شیبر"],
                ["code" => "" , "province_id" => "10", "district_en"=> "SAIGHAN", "district_dr"=> "سیغان", "district_ps" => "سیغان"],
                ["code" => "" , "province_id" => "10", "district_en"=> "KAHMARD", "district_dr"=> "کهمرد", "district_ps" => "کهمرد"],
                ["code" => "" , "province_id" => "10", "district_en"=> "YAKAWLANG", "district_dr"=> "یکاولنگ", "district_ps" => "یکاولنگ"],
                ["code" => "" , "province_id" => "10", "district_en"=> "PANJAB", "district_dr"=> "پنجاب", "district_ps" => "پنجاب"],
                ["code" => "" , "province_id" => "10", "district_en"=> "WARAS", "district_dr"=> "ورس", "district_ps" => "ورس"],
                ["code" => "" , "province_id" => "10", "district_en"=> "BATOO", "district_dr"=> "باتو", "district_ps" => "باتو"],
                ["code" => "" , "province_id" => "10", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "11", "district_en"=> "(Capital) GHAZNI", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "11", "district_en"=> "WALI MOHAMMAD SHAHID KHUGYANI", "district_dr"=> "ولی محمد شهید خوگیانی", "district_ps" => "ولی محمد شهید خوگیانی"],
                ["code" => "" , "province_id" => "11", "district_en"=> "KHWAJA OMARI", "district_dr"=> "خواجه عمری", "district_ps" => "خواجه عمری"],
                ["code" => "" , "province_id" => "11", "district_en"=> "WAGHAZ", "district_dr"=> "واغظ", "district_ps" => "واغظ"],
                ["code" => "" , "province_id" => "11", "district_en"=> "DEH YAK", "district_dr"=> "ده یک", "district_ps" => "ده یک"],
                ["code" => "" , "province_id" => "11", "district_en"=> "JAGHATU", "district_dr"=> "جغتو", "district_ps" => "جغتو"],
                ["code" => "" , "province_id" => "11", "district_en"=> "ANDAR", "district_dr"=> "اندر", "district_ps" => "اندر"],
                ["code" => "" , "province_id" => "11", "district_en"=> "ZANAKHAN", "district_dr"=> "زنخان", "district_ps" => "زنخان"],
                ["code" => "" , "province_id" => "11", "district_en"=> "RASHIDAN", "district_dr"=> "رشیدان", "district_ps" => "رشیدان"],
                ["code" => "" , "province_id" => "11", "district_en"=> "NAWUR", "district_dr"=> "ناور", "district_ps" => "ناور"],
                ["code" => "" , "province_id" => "11", "district_en"=> "QARA BAGH", "district_dr"=> "قره باغ", "district_ps" => "قره باغ"],
                ["code" => "" , "province_id" => "11", "district_en"=> "GIRO", "district_dr"=> "گیرو", "district_ps" => "گیرو"],
                ["code" => "" , "province_id" => "11", "district_en"=> "AB BAND", "district_dr"=> "آب بند", "district_ps" => "آب بند"],
                ["code" => "" , "province_id" => "11", "district_en"=> "JAGHURI", "district_dr"=> "جاغوری", "district_ps" => "جاغوری"],
                ["code" => "" , "province_id" => "11", "district_en"=> "MUQUR", "district_dr"=> "مقر", "district_ps" => "مقر"],
                ["code" => "" , "province_id" => "11", "district_en"=> "MALISTAN", "district_dr"=> "مالستان", "district_ps" => "مالستان"],
                ["code" => "" , "province_id" => "11", "district_en"=> "GELAN", "district_dr"=> "گیلان", "district_ps" => "گیلان"],
                ["code" => "" , "province_id" => "11", "district_en"=> "AJRISTAN", "district_dr"=> "اجرستان", "district_ps" => "اجرستان"],
                ["code" => "" , "province_id" => "11", "district_en"=> "NAWA", "district_dr"=> "ناوه", "district_ps" => "ناوه"],
                ["code" => "" , "province_id" => "11", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "12", "district_en"=> "(Capital) SHARAN", "district_dr"=> "مرکز(شرن)", "district_ps" => "مرکز(شرن)"],
                ["code" => "" , "province_id" => "12", "district_en"=> "MATA KHAN", "district_dr"=> "متاخان", "district_ps" => "متاخان"],
                ["code" => "" , "province_id" => "12", "district_en"=> "YOSUF KHEL", "district_dr"=> "یوسف خیل", "district_ps" => "یوسف خیل"],
                ["code" => "" , "province_id" => "12", "district_en"=> "YAHYA KHEL", "district_dr"=> "یحیی خیل", "district_ps" => "یحیی خیل"],
                ["code" => "" , "province_id" => "12", "district_en"=> "SAR RAWZA", "district_dr"=> "سرروضه", "district_ps" => "سرروضه"],
                ["code" => "" , "province_id" => "12", "district_en"=> "OMNA", "district_dr"=> "اومنه", "district_ps" => "اومنه"],
                ["code" => "" , "province_id" => "12", "district_en"=> "ZARGHUN SHAHR", "district_dr"=> "زرغون شهر", "district_ps" => "زرغون شهر"],
                ["code" => "" , "province_id" => "12", "district_en"=> "GOMAL", "district_dr"=> "گومل", "district_ps" => "گومل"],
                ["code" => "" , "province_id" => "12", "district_en"=> "JANI KHEL", "district_dr"=> "جانی خیل", "district_ps" => "جانی خیل"],
                ["code" => "" , "province_id" => "12", "district_en"=> "SURUBI", "district_dr"=> "سروبی", "district_ps" => "سروبی"],
                ["code" => "" , "province_id" => "12", "district_en"=> "URGOON", "district_dr"=> "اورگون", "district_ps" => "اورگون"],
                ["code" => "" , "province_id" => "12", "district_en"=> "ZIRUK", "district_dr"=> "زیروک", "district_ps" => "زیروک"],
                ["code" => "" , "province_id" => "12", "district_en"=> "NIKA", "district_dr"=> "نیکه", "district_ps" => "نیکه"],
                ["code" => "" , "province_id" => "12", "district_en"=> "BARMAL", "district_dr"=> "برمل", "district_ps" => "برمل"],
                ["code" => "" , "province_id" => "12", "district_en"=> "GIYAN", "district_dr"=> "گیان", "district_ps" => "گیان"],
                ["code" => "" , "province_id" => "12", "district_en"=> "DILA WA KHUSHAMAND", "district_dr"=> "دیله و خوش آمند", "district_ps" => "دیله و خوش آمند"],
                ["code" => "" , "province_id" => "12", "district_en"=> "WAZAKHWAH", "district_dr"=> "وازه خوا", "district_ps" => "وازه خوا"],
                ["code" => "" , "province_id" => "12", "district_en"=> "WORMAMAY", "district_dr"=> "ورممی", "district_ps" => "ورممی"],
                ["code" => "" , "province_id" => "12", "district_en"=> "TURWO", "district_dr"=> "تروو", "district_ps" => "تروو"],
                ["code" => "" , "province_id" => "12", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "13", "district_en"=> "(Capital) GARDEZ", "district_dr"=> "مرکز(گردیز)", "district_ps" => "مرکز(گردیز)"],
                ["code" => "" , "province_id" => "13", "district_en"=> "AHMADABA", "district_dr"=> "احمدآبا", "district_ps" => "احمدآبا"],
                ["code" => "" , "province_id" => "13", "district_en"=> "ZURMAT", "district_dr"=> "زرمت", "district_ps" => "زرمت"],
                ["code" => "" , "province_id" => "13", "district_en"=> "SHWAK", "district_dr"=> "شواک", "district_ps" => "شواک"],
                ["code" => "" , "province_id" => "13", "district_en"=> "WUZA ZADRAN", "district_dr"=> "وزی ځدران", "district_ps" => "وزی ځدران"],
                ["code" => "" , "province_id" => "13", "district_en"=> "SAYYID KARAM", "district_dr"=> "سیدکرم", "district_ps" => "سیدکرم"],
                ["code" => "" , "province_id" => "13", "district_en"=> "JAJI", "district_dr"=> "جاجی", "district_ps" => "جاجی"],
                ["code" => "" , "province_id" => "13", "district_en"=> "LAJA AHMAD KHEL", "district_dr"=> "لجه احمدخیل", "district_ps" => "لجه احمدخیل"],
                ["code" => "" , "province_id" => "13", "district_en"=> "JANI KHEL", "district_dr"=> "جانی خیل", "district_ps" => "جانی خیل"],
                ["code" => "" , "province_id" => "13", "district_en"=> "SAMKANI", "district_dr"=> "څمکنی", "district_ps" => "څمکنی"],
                ["code" => "" , "province_id" => "13", "district_en"=> "DAND PATAN", "district_dr"=> "دند پتان", "district_ps" => "دند پتان"],
                ["code" => "" , "province_id" => "13", "district_en"=> "GERDA KHEBRI", "district_dr"=> "گرده خبری", "district_ps" => "گرده خبری"],
                ["code" => "" , "province_id" => "13", "district_en"=> "MEERZAKA", "district_dr"=> "میرزکه", "district_ps" => "میرزکه"],
                ["code" => "" , "province_id" => "13", "district_en"=> "LAJA MANGAL", "district_dr"=> "لجه منگل", "district_ps" => "لجه منگل"],
                ["code" => "" , "province_id" => "13", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "14", "district_en"=> "(Capital) KHOST", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "14", "district_en"=> "MANDUZAY (ESMAYEL KHEL)", "district_dr"=> "(مندوزی) اسماعیل خیل", "district_ps" => "(مندوزی) اسماعیل خیل"],
                ["code" => "" , "province_id" => "14", "district_en"=> "GURBUZ", "district_dr"=> "گربز", "district_ps" => "گربز"],
                ["code" => "" , "province_id" => "14", "district_en"=> "TANAY", "district_dr"=> "تنی", "district_ps" => "تنی"],
                ["code" => "" , "province_id" => "14", "district_en"=> "MUSA KHEL", "district_dr"=> "موسی خیل", "district_ps" => "موسی خیل"],
                ["code" => "" , "province_id" => "14", "district_en"=> "NADIRSHAH KOT", "district_dr"=> "نادرشاه کوت", "district_ps" => "نادرشاه کوت"],
                ["code" => "" , "province_id" => "14", "district_en"=> "SABARI (YAQUBI)", "district_dr"=> "(صبری) یعقوبی", "district_ps" => "(صبری) یعقوبی"],
                ["code" => "" , "province_id" => "14", "district_en"=> "ALI SHER", "district_dr"=> "علی شیر", "district_ps" => "علی شیر"],
                ["code" => "" , "province_id" => "14", "district_en"=> "BAAK", "district_dr"=> "باک", "district_ps" => "باک"],
                ["code" => "" , "province_id" => "14", "district_en"=> "QALANDAR", "district_dr"=> "قلندر", "district_ps" => "قلندر"],
                ["code" => "" , "province_id" => "14", "district_en"=> "SPERA", "district_dr"=> "اسپیره", "district_ps" => "اسپیره"],
                ["code" => "" , "province_id" => "14", "district_en"=> "SHAMUL", "district_dr"=> "شمل", "district_ps" => "شمل"],
                ["code" => "" , "province_id" => "14", "district_en"=> "ZAZI MAIDAN", "district_dr"=> "ځاځی میدان", "district_ps" => "ځاځی میدان"],
                ["code" => "" , "province_id" => "14", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "15", "district_en"=> "(Capital) ASAD ABAD", "district_dr"=> "مرکز(اسدآباد)", "district_ps" => "مرکز(اسدآباد)"],
                ["code" => "" , "province_id" => "15", "district_en"=> "MARA WARA", "district_dr"=> "مره وره", "district_ps" => "مره وره"],
                ["code" => "" , "province_id" => "15", "district_en"=> "WATAPOOR", "district_dr"=> "واته پور", "district_ps" => "واته پور"],
                ["code" => "" , "province_id" => "15", "district_en"=> "NARANG WA BADIL", "district_dr"=> "نرنگ وبادیل", "district_ps" => "نرنگ وبادیل"],
                ["code" => "" , "province_id" => "15", "district_en"=> "SAR KANI", "district_dr"=> "سرکانی", "district_ps" => "سرکانی"],
                ["code" => "" , "province_id" => "15", "district_en"=> "SHIGAL WA SHELTAN", "district_dr"=> "شیگل و شیلتن", "district_ps" => "شیگل و شیلتن"],
                ["code" => "" , "province_id" => "15", "district_en"=> "DARA-E-PECH", "district_dr"=> "دره پیچ", "district_ps" => "دره پیچ"],
                ["code" => "" , "province_id" => "15", "district_en"=> "BAR KUNAR", "district_dr"=> "برکنر", "district_ps" => "برکنر"],
                ["code" => "" , "province_id" => "15", "district_en"=> "SAWKAI", "district_dr"=> "څوکی", "district_ps" => "څوکی"],
                ["code" => "" , "province_id" => "15", "district_en"=> "KHAS KUNAR", "district_dr"=> "خاص کنر", "district_ps" => "خاص کنر"],
                ["code" => "" , "province_id" => "15", "district_en"=> "GHAZI ABAD", "district_dr"=> "غازی آباد", "district_ps" => "غازی آباد"],
                ["code" => "" , "province_id" => "15", "district_en"=> "DANGAM", "district_dr"=> "دانگام", "district_ps" => "دانگام"],
                ["code" => "" , "province_id" => "15", "district_en"=> "CHAPA DARA", "district_dr"=> "چپه دره", "district_ps" => "چپه دره"],
                ["code" => "" , "province_id" => "15", "district_en"=> "NOOR GAL", "district_dr"=> "نورگل", "district_ps" => "نورگل"],
                ["code" => "" , "province_id" => "15", "district_en"=> "NARI", "district_dr"=> "نری", "district_ps" => "نری"],
                ["code" => "" , "province_id" => "15", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "16", "district_en"=> "(Capital) PAROON", "district_dr"=> "مرکز(پارون)", "district_ps" => "مرکز(پارون)"],
                ["code" => "" , "province_id" => "16", "district_en"=> "WAYGAL", "district_dr"=> "وایگل", "district_ps" => "وایگل"],
                ["code" => "" , "province_id" => "16", "district_en"=> "WAMA", "district_dr"=> "واما", "district_ps" => "واما"],
                ["code" => "" , "province_id" => "16", "district_en"=> "NOOR GRAM", "district_dr"=> "نورگرام", "district_ps" => "نورگرام"],
                ["code" => "" , "province_id" => "16", "district_en"=> "DUAB", "district_dr"=> "دوآب", "district_ps" => "دوآب"],
                ["code" => "" , "province_id" => "16", "district_en"=> "KAMDESH", "district_dr"=> "کامدیش", "district_ps" => "کامدیش"],
                ["code" => "" , "province_id" => "16", "district_en"=> "MANDOL", "district_dr"=> "مندول", "district_ps" => "مندول"],
                ["code" => "" , "province_id" => "16", "district_en"=> "BARG-E-MATAL", "district_dr"=> "برگ متال", "district_ps" => "برگ متال"],
                ["code" => "" , "province_id" => "16", "district_en"=> "Pargmatal", "district_dr"=> "برګمتال", "district_ps" => "برګمتال"],
                ["code" => "" , "province_id" => "16", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "17", "district_en"=> "(Capital) FAIZ ABAD", "district_dr"=> "مرکز(فیض آباد)", "district_ps" => "مرکز(فیض آباد)"],
                ["code" => "" , "province_id" => "17", "district_en"=> "ARGO", "district_dr"=> "ارگو", "district_ps" => "ارگو"],
                ["code" => "" , "province_id" => "17", "district_en"=> "ARGHANJ KHWAH", "district_dr"=> "ارغنجخواه", "district_ps" => "ارغنجخواه"],
                ["code" => "" , "province_id" => "17", "district_en"=> "YAFTAL-E-SOFLA", "district_dr"=> "یفتل سفلی", "district_ps" => "یفتل سفلی"],
                ["code" => "" , "province_id" => "17", "district_en"=> "KHASH", "district_dr"=> "خاش", "district_ps" => "خاش"],
                ["code" => "" , "province_id" => "17", "district_en"=> "BAHARAK", "district_dr"=> "بهارک", "district_ps" => "بهارک"],
                ["code" => "" , "province_id" => "17", "district_en"=> "DARAYIM", "district_dr"=> "درایم", "district_ps" => "درایم"],
                ["code" => "" , "province_id" => "17", "district_en"=> "KOHISTAN", "district_dr"=> "کوهستان", "district_ps" => "کوهستان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "YAWAN", "district_dr"=> "یاوان", "district_ps" => "یاوان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "JURM", "district_dr"=> "جرم", "district_ps" => "جرم"],
                ["code" => "" , "province_id" => "17", "district_en"=> "TASHKAN", "district_dr"=> "تشکان", "district_ps" => "تشکان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "SHUHADA", "district_dr"=> "شهدا", "district_ps" => "شهدا"],
                ["code" => "" , "province_id" => "17", "district_en"=> "SHAHR-E-BUZURG", "district_dr"=> "شهربزرگ", "district_ps" => "شهربزرگ"],
                ["code" => "" , "province_id" => "17", "district_en"=> "RAGHISTAN", "district_dr"=> "راغستان", "district_ps" => "راغستان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "KISHM", "district_dr"=> "کشم", "district_ps" => "کشم"],
                ["code" => "" , "province_id" => "17", "district_en"=> "WARDOOJ", "district_dr"=> "وردوج", "district_ps" => "وردوج"],
                ["code" => "" , "province_id" => "17", "district_en"=> "TAGAB", "district_dr"=> "تگاب", "district_ps" => "تگاب"],
                ["code" => "" , "province_id" => "17", "district_en"=> "YAMGAN", "district_dr"=> "یمگان", "district_ps" => "یمگان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "SHIGHNAN", "district_dr"=> "شغنان", "district_ps" => "شغنان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "KHWAHAN", "district_dr"=> "خواهان", "district_ps" => "خواهان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "KUFAB", "district_dr"=> "کوف آب", "district_ps" => "کوف آب"],
                ["code" => "" , "province_id" => "17", "district_en"=> "DARWAZ-E-PAYIN (MAMAY)", "district_dr"=> "درواز پائین مایمی", "district_ps" => "درواز پائین مایمی"],
                ["code" => "" , "province_id" => "17", "district_en"=> "ESHKASHIM", "district_dr"=> "اشکاشم", "district_ps" => "اشکاشم"],
                ["code" => "" , "province_id" => "17", "district_en"=> "SHIKI", "district_dr"=> "شکی", "district_ps" => "شکی"],
                ["code" => "" , "province_id" => "17", "district_en"=> "ZEBAK", "district_dr"=> "زیباک", "district_ps" => "زیباک"],
                ["code" => "" , "province_id" => "17", "district_en"=> "KIRAN WA MENJAN", "district_dr"=> "کران ومنجان", "district_ps" => "کران ومنجان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "DARWAZ-E-BALA (NESAY)", "district_dr"=> "درواز بالا نسی", "district_ps" => "درواز بالا نسی"],
                ["code" => "" , "province_id" => "17", "district_en"=> "WAKHAN", "district_dr"=> "واخان", "district_ps" => "واخان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 1 ", "district_dr"=> "ناحیه 1 ", "district_ps" => "ناحیه 1 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 2 ", "district_dr"=> "ناحیه 2 ", "district_ps" => "ناحیه 2 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 3 ", "district_dr"=> "ناحیه 3 ", "district_ps" => "ناحیه 3 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 4 ", "district_dr"=> "ناحیه 4 ", "district_ps" => "ناحیه 4 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 5 ", "district_dr"=> "ناحیه 5 ", "district_ps" => "ناحیه 5 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 6 ", "district_dr"=> "ناحیه 6 ", "district_ps" => "ناحیه 6 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 7 ", "district_dr"=> "ناحیه 7 ", "district_ps" => "ناحیه 7 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 8 ", "district_dr"=> "ناحیه 8 ", "district_ps" => "ناحیه 8 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 9 ", "district_dr"=> "ناحیه 9 ", "district_ps" => "ناحیه 9 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 10 ", "district_dr"=> "ناحیه 10 ", "district_ps" => "ناحیه 10 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "PD 11 ", "district_dr"=> "ناحیه 11 ", "district_ps" => "ناحیه 11 "],
                ["code" => "" , "province_id" => "17", "district_en"=> "TESHGAN", "district_dr"=> "تیشگان", "district_ps" => "تیشگان"],
                ["code" => "" , "province_id" => "17", "district_en"=> "DARWAZ-E-BALA (MAYME)", "district_dr"=> "درواز بالا مایمی", "district_ps" => "درواز بالا مایمی"],
                ["code" => "" , "province_id" => "17", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "18", "district_en"=> "(Capital) TALUQAN", "district_dr"=> "مرکز(تالقان)", "district_ps" => "مرکز(تالقان)"],
                ["code" => "" , "province_id" => "18", "district_en"=> "HAZAR SUMUCH", "district_dr"=> "هزارسموچ", "district_ps" => "هزارسموچ"],
                ["code" => "" , "province_id" => "18", "district_en"=> "BAHARAK", "district_dr"=> "بهارک", "district_ps" => "بهارک"],
                ["code" => "" , "province_id" => "18", "district_en"=> "BANGI", "district_dr"=> "بنگی", "district_ps" => "بنگی"],
                ["code" => "" , "province_id" => "18", "district_en"=> "CHAL", "district_dr"=> "چال", "district_ps" => "چال"],
                ["code" => "" , "province_id" => "18", "district_en"=> "NAMAK AB", "district_dr"=> "نمک آب", "district_ps" => "نمک آب"],
                ["code" => "" , "province_id" => "18", "district_en"=> "KALAFGAN", "district_dr"=> "کلفگان", "district_ps" => "کلفگان"],
                ["code" => "" , "province_id" => "18", "district_en"=> "FARKHAR", "district_dr"=> "فرخار", "district_ps" => "فرخار"],
                ["code" => "" , "province_id" => "18", "district_en"=> "KHWAJA GHAR", "district_dr"=> "خواجه غار", "district_ps" => "خواجه غار"],
                ["code" => "" , "province_id" => "18", "district_en"=> "RUSTAQ", "district_dr"=> "رستاق", "district_ps" => "رستاق"],
                ["code" => "" , "province_id" => "18", "district_en"=> "ESHKAMESH", "district_dr"=> "اشکمش", "district_ps" => "اشکمش"],
                ["code" => "" , "province_id" => "18", "district_en"=> "DASHT-E-QALA", "district_dr"=> "دشت قلعه", "district_ps" => "دشت قلعه"],
                ["code" => "" , "province_id" => "18", "district_en"=> "WARSAJ", "district_dr"=> "ورسج", "district_ps" => "ورسج"],
                ["code" => "" , "province_id" => "18", "district_en"=> "KHWAJA BAHAWUDDIN", "district_dr"=> "خواجه بهاوالدین", "district_ps" => "خواجه بهاوالدین"],
                ["code" => "" , "province_id" => "18", "district_en"=> "DARQAD", "district_dr"=> "درقد", "district_ps" => "درقد"],
                ["code" => "" , "province_id" => "18", "district_en"=> "CHAHAB", "district_dr"=> "چاه آب", "district_ps" => "چاه آب"],
                ["code" => "" , "province_id" => "18", "district_en"=> "YANGI QALA", "district_dr"=> "ینگی قلعه", "district_ps" => "ینگی قلعه"],
                ["code" => "" , "province_id" => "18", "district_en"=> "PD 1 ", "district_dr"=> "ناحیه 1 ", "district_ps" => "ناحیه 1 "],
                ["code" => "" , "province_id" => "18", "district_en"=> "PD 2 ", "district_dr"=> "ناحیه 2 ", "district_ps" => "ناحیه 2 "],
                ["code" => "" , "province_id" => "18", "district_en"=> "PD 3 ", "district_dr"=> "ناحیه 3 ", "district_ps" => "ناحیه 3 "],
                ["code" => "" , "province_id" => "18", "district_en"=> "PD 4 ", "district_dr"=> "ناحیه 4 ", "district_ps" => "ناحیه 4 "],
                ["code" => "" , "province_id" => "18", "district_en"=> "Gul bad", "district_dr"=> "کل باد", "district_ps" => "کل باد"],
                ["code" => "" , "province_id" => "18", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "19", "district_en"=> "(Capital) KUNDUZ", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "19", "district_en"=> "CHAR DARAH", "district_dr"=> "چاردره", "district_ps" => "چاردره"],
                ["code" => "" , "province_id" => "19", "district_en"=> "ALI ABAD", "district_dr"=> "علی آباد", "district_ps" => "علی آباد"],
                ["code" => "" , "province_id" => "19", "district_en"=> "KHAN ABAD", "district_dr"=> "خان آباد", "district_ps" => "خان آباد"],
                ["code" => "" , "province_id" => "19", "district_en"=> "HAZRATI IMAM SAHIB", "district_dr"=> "حضرت امام صاحب", "district_ps" => "حضرت امام صاحب"],
                ["code" => "" , "province_id" => "19", "district_en"=> "DASHTI-E-ARCHI", "district_dr"=> "دشت ارچی", "district_ps" => "دشت ارچی"],
                ["code" => "" , "province_id" => "19", "district_en"=> "QALA-E-ZAL", "district_dr"=> "قلعه ذال", "district_ps" => "قلعه ذال"],
                ["code" => "" , "province_id" => "19", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "19", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "19", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "19", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "19", "district_en"=> "PD 5", "district_dr"=> "ناحیه 5", "district_ps" => "ناحیه 5"],
                ["code" => "" , "province_id" => "19", "district_en"=> "GUL TAPA (MOWAQAT)", "district_dr"=> "ګل تپه (موقت)", "district_ps" => "ګل تپه (موقت)"],
                ["code" => "" , "province_id" => "19", "district_en"=> "KALBAAD", "district_dr"=> "کلباد", "district_ps" => "کلباد"],
                ["code" => "" , "province_id" => "19", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "20", "district_en"=> "(Capital) AYBAK", "district_dr"=> "مرکز(ایبک)", "district_ps" => "مرکز(ایبک)"],
                ["code" => "" , "province_id" => "19", "district_en"=> "AAQTASH (MOWAQAT)", "district_dr"=> "آقتاش (موقت)", "district_ps" => "آقتاش (موقت)"],
                ["code" => "" , "province_id" => "20", "district_en"=> "HAZRAT-E-SULTAN", "district_dr"=> "حضرت سلطان", "district_ps" => "حضرت سلطان"],
                ["code" => "" , "province_id" => "20", "district_en"=> "KHURAM WA SARBAGH", "district_dr"=> "خرم و سارباغ", "district_ps" => "خرم و سارباغ"],
                ["code" => "" , "province_id" => "20", "district_en"=> "FEROZ NAKHCHEER", "district_dr"=> "فیروزنخچیر", "district_ps" => "فیروزنخچیر"],
                ["code" => "" , "province_id" => "20", "district_en"=> "ROI-DO-AB", "district_dr"=> "روی دوآب", "district_ps" => "روی دوآب"],
                ["code" => "" , "province_id" => "20", "district_en"=> "DARA-E-SOOF-E-PAYIN", "district_dr"=> "دره صوف پائین", "district_ps" => "دره صوف پائین"],
                ["code" => "" , "province_id" => "20", "district_en"=> "DARA-E-SOOF-E-BALA", "district_dr"=> "دره صوف  بالا", "district_ps" => "دره صوف  بالا"],
                ["code" => "" , "province_id" => "20", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "20", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "20", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "20", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "21", "district_en"=> "(Capital) Mazar-e-sharif", "district_dr"=> "مرکز(مزار شریف)", "district_ps" => "مرکز(مزار شریف)"],
                ["code" => "" , "province_id" => "21", "district_en"=> "NAHR-E-SHAHI", "district_dr"=> "نهر شاهی", "district_ps" => "نهر شاهی"],
                ["code" => "" , "province_id" => "21", "district_en"=> "DEHDADI", "district_dr"=> "دهدادی", "district_ps" => "دهدادی"],
                ["code" => "" , "province_id" => "21", "district_en"=> "CHAR KENT", "district_dr"=> "چارکنت", "district_ps" => "چارکنت"],
                ["code" => "" , "province_id" => "21", "district_en"=> "MARMUL", "district_dr"=> "مارمل", "district_ps" => "مارمل"],
                ["code" => "" , "province_id" => "21", "district_en"=> "BALKH", "district_dr"=> "بلخ", "district_ps" => "بلخ"],
                ["code" => "" , "province_id" => "21", "district_en"=> "SHOLGARA", "district_dr"=> "شولگره", "district_ps" => "شولگره"],
                ["code" => "" , "province_id" => "21", "district_en"=> "CHIMTAL", "district_dr"=> "چمتال", "district_ps" => "چمتال"],
                ["code" => "" , "province_id" => "21", "district_en"=> "DAWLAT ABAD", "district_dr"=> "دولت آباد", "district_ps" => "دولت آباد"],
                ["code" => "" , "province_id" => "21", "district_en"=> "KHULM", "district_dr"=> "خلم", "district_ps" => "خلم"],
                ["code" => "" , "province_id" => "21", "district_en"=> "CHAR BOLAK", "district_dr"=> "چاربولک", "district_ps" => "چاربولک"],
                ["code" => "" , "province_id" => "21", "district_en"=> "SHORTEPA", "district_dr"=> "شورتیپه", "district_ps" => "شورتیپه"],
                ["code" => "" , "province_id" => "21", "district_en"=> "KALDAR", "district_dr"=> "کلدار", "district_ps" => "کلدار"],
                ["code" => "" , "province_id" => "21", "district_en"=> "KISHINDEH", "district_dr"=> "کشنده", "district_ps" => "کشنده"],
                ["code" => "" , "province_id" => "21", "district_en"=> "ZARI", "district_dr"=> "زاری", "district_ps" => "زاری"],
                ["code" => "" , "province_id" => "21", "district_en"=> "Ailaq che paeen", "district_dr"=> "ایلقچی پاین", "district_ps" => "ایلقچی پاین"],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 1 ", "district_dr"=> "ناحیه 1 ", "district_ps" => "ناحیه 1 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 2 ", "district_dr"=> "ناحیه 2 ", "district_ps" => "ناحیه 2 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 3 ", "district_dr"=> "ناحیه 3 ", "district_ps" => "ناحیه 3 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 4 ", "district_dr"=> "ناحیه 4 ", "district_ps" => "ناحیه 4 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 5 ", "district_dr"=> "ناحیه 5 ", "district_ps" => "ناحیه 5 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 6 ", "district_dr"=> "ناحیه 6 ", "district_ps" => "ناحیه 6 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 7 ", "district_dr"=> "ناحیه 7 ", "district_ps" => "ناحیه 7 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 8 ", "district_dr"=> "ناحیه 8 ", "district_ps" => "ناحیه 8 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "PD 9 ", "district_dr"=> "ناحیه 9 ", "district_ps" => "ناحیه 9 "],
                ["code" => "" , "province_id" => "21", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "22", "district_en"=> "(Capital) SAR-E-PUL", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "22", "district_en"=> "SAYYAD", "district_dr"=> "صیاد", "district_ps" => "صیاد"],
                ["code" => "" , "province_id" => "22", "district_en"=> "KOHISTANAT", "district_dr"=> "کوهستانات", "district_ps" => "کوهستانات"],
                ["code" => "" , "province_id" => "22", "district_en"=> "SOZMA QALA", "district_dr"=> "سوزمه قلعه", "district_ps" => "سوزمه قلعه"],
                ["code" => "" , "province_id" => "22", "district_en"=> "SANGCHARAK", "district_dr"=> "سنگ چارک", "district_ps" => "سنگ چارک"],
                ["code" => "" , "province_id" => "22", "district_en"=> "GOSFANDI", "district_dr"=> "گوسفندی", "district_ps" => "گوسفندی"],
                ["code" => "" , "province_id" => "22", "district_en"=> "BALKHAB", "district_dr"=> "بلخاب", "district_ps" => "بلخاب"],
                ["code" => "" , "province_id" => "22", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "22", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "22", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "22", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "23", "district_en"=> "(Capital) CHIGHCHERAN", "district_dr"=> "مرکز(چغچران)", "district_ps" => "مرکز(چغچران)"],
                ["code" => "" , "province_id" => "23", "district_en"=> "DULEENA", "district_dr"=> "دولینه", "district_ps" => "دولینه"],
                ["code" => "" , "province_id" => "23", "district_en"=> "DAWLATYAR", "district_dr"=> "دولت یار", "district_ps" => "دولت یار"],
                ["code" => "" , "province_id" => "23", "district_en"=> "CHAR SADA", "district_dr"=> "چارصده", "district_ps" => "چارصده"],
                ["code" => "" , "province_id" => "23", "district_en"=> "PASABAND", "district_dr"=> "پسابند", "district_ps" => "پسابند"],
                ["code" => "" , "province_id" => "23", "district_en"=> "SHAHRAK", "district_dr"=> "شهرک", "district_ps" => "شهرک"],
                ["code" => "" , "province_id" => "23", "district_en"=> "LAL WA SARJANGAL", "district_dr"=> "لعل وسرجنگل", "district_ps" => "لعل وسرجنگل"],
                ["code" => "" , "province_id" => "23", "district_en"=> "TAYWARA", "district_dr"=> "تیوره", "district_ps" => "تیوره"],
                ["code" => "" , "province_id" => "23", "district_en"=> "TULAK", "district_dr"=> "تولک", "district_ps" => "تولک"],
                ["code" => "" , "province_id" => "23", "district_en"=> "SAGHAR", "district_dr"=> "ساغر", "district_ps" => "ساغر"],
                ["code" => "" , "province_id" => "23", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "23", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "23", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "23", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "23", "district_en"=> "FEROZ KHOH", "district_dr"=> "فیروز کوه", "district_ps" => "فیروز کوه"],
                ["code" => "" , "province_id" => "23", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "24", "district_en"=> "(Capital) NILI", "district_dr"=> "مرکز(نیلی)", "district_ps" => "مرکز(نیلی)"],
                ["code" => "" , "province_id" => "24", "district_en"=> "PATO", "district_dr"=> "پاتو", "district_ps" => "پاتو"],
                ["code" => "" , "province_id" => "24", "district_en"=> "NAWA MISH", "district_dr"=> "ناوه میش", "district_ps" => "ناوه میش"],
                ["code" => "" , "province_id" => "24", "district_en"=> "SHAHRISTAN", "district_dr"=> "شهرستان", "district_ps" => "شهرستان"],
                ["code" => "" , "province_id" => "24", "district_en"=> "GIZAB", "district_dr"=> "گیزاب", "district_ps" => "گیزاب"],
                ["code" => "" , "province_id" => "24", "district_en"=> "ISHTERLAI", "district_dr"=> "اشترلی", "district_ps" => "اشترلی"],
                ["code" => "" , "province_id" => "24", "district_en"=> "KHEDIR", "district_dr"=> "خدیر", "district_ps" => "خدیر"],
                ["code" => "" , "province_id" => "24", "district_en"=> "GETI", "district_dr"=> "گیتی", "district_ps" => "گیتی"],
                ["code" => "" , "province_id" => "24", "district_en"=> "MIRAMOR", "district_dr"=> "میرامور", "district_ps" => "میرامور"],
                ["code" => "" , "province_id" => "24", "district_en"=> "SANG-E-TAKHT", "district_dr"=> "سنگ تخت", "district_ps" => "سنگ تخت"],
                ["code" => "" , "province_id" => "24", "district_en"=> "KEJRAN", "district_dr"=> "کیجران", "district_ps" => "کیجران"],
                ["code" => "" , "province_id" => "24", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "24", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "25", "district_en"=> "(Capital) TIRINKOT", "district_dr"=> "مرکز(ترینکوت)", "district_ps" => "مرکز(ترینکوت)"],
                ["code" => "" , "province_id" => "25", "district_en"=> "DEHRAOUD", "district_dr"=> "دهراود", "district_ps" => "دهراود"],
                ["code" => "" , "province_id" => "25", "district_en"=> "CHORA", "district_dr"=> "چوره", "district_ps" => "چوره"],
                ["code" => "" , "province_id" => "25", "district_en"=> "SHAHID-E-HASSAS", "district_dr"=> "شهید حساس", "district_ps" => "شهید حساس"],
                ["code" => "" , "province_id" => "25", "district_en"=> "KHAS UROZGAN", "district_dr"=> "خاص ارزگان", "district_ps" => "خاص ارزگان"],
                ["code" => "" , "province_id" => "25", "district_en"=> "PD 1 ", "district_dr"=> "ناحیه 1 ", "district_ps" => "ناحیه 1 "],
                ["code" => "" , "province_id" => "25", "district_en"=> "PD 2 ", "district_dr"=> "ناحیه 2 ", "district_ps" => "ناحیه 2 "],
                ["code" => "" , "province_id" => "25", "district_en"=> "PD 3 ", "district_dr"=> "ناحیه 3 ", "district_ps" => "ناحیه 3 "],
                ["code" => "" , "province_id" => "25", "district_en"=> "PD 4 ", "district_dr"=> "ناحیه 4 ", "district_ps" => "ناحیه 4 "],
                ["code" => "" , "province_id" => "25", "district_en"=> "Chahar Chino", "district_dr"=> "چهارچینو", "district_ps" => "چهارچینو"],
                ["code" => "" , "province_id" => "25", "district_en"=> "CHENARTO", "district_dr"=> "چنارتو", "district_ps" => "چنارتو"],
                ["code" => "" , "province_id" => "25", "district_en"=> "GAZAAB", "district_dr"=> "گزاب", "district_ps" => "گزاب"],
                ["code" => "" , "province_id" => "25", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "26", "district_en"=> "(Capital) QALAT", "district_dr"=> "مرکز(قلات)", "district_ps" => "مرکز(قلات)"],
                ["code" => "" , "province_id" => "26", "district_en"=> "TARANK WA JALDAK", "district_dr"=> "ترنک وجلدک", "district_ps" => "ترنک وجلدک"],
                ["code" => "" , "province_id" => "26", "district_en"=> "SHINKAI", "district_dr"=> "شینکی", "district_ps" => "شینکی"],
                ["code" => "" , "province_id" => "26", "district_en"=> "MIZAN", "district_dr"=> "میزان", "district_ps" => "میزان"],
                ["code" => "" , "province_id" => "26", "district_en"=> "ARGHANDAB", "district_dr"=> "ارغنداب", "district_ps" => "ارغنداب"],
                ["code" => "" , "province_id" => "26", "district_en"=> "SHAH JOI", "district_dr"=> "شاه جوی", "district_ps" => "شاه جوی"],
                ["code" => "" , "province_id" => "26", "district_en"=> "DAICHOPAN", "district_dr"=> "دایچوپان", "district_ps" => "دایچوپان"],
                ["code" => "" , "province_id" => "26", "district_en"=> "ATGHAR", "district_dr"=> "اتغر", "district_ps" => "اتغر"],
                ["code" => "" , "province_id" => "26", "district_en"=> "NAW BAHAR", "district_dr"=> "نوبهار", "district_ps" => "نوبهار"],
                ["code" => "" , "province_id" => "26", "district_en"=> "SHEMEL ZAYEE", "district_dr"=> "شملزایی", "district_ps" => "شملزایی"],
                ["code" => "" , "province_id" => "26", "district_en"=> "KAKARI (KHAK-E-AFGHAN)", "district_dr"=> "(کاکری) خاک افغان", "district_ps" => "(کاکری) خاک افغان"],
                ["code" => "" , "province_id" => "26", "district_en"=> "Shahrak Safa ", "district_dr"=> "شهرصفاء (نرنگ و جلدک)", "district_ps" => "شهرصفاء (نرنگ و جلدک)"],
                ["code" => "" , "province_id" => "26", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "27", "district_en"=> "(Capital) KANDAHAR", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "27", "district_en"=> "ARGHANDAB", "district_dr"=> "ارغنداب", "district_ps" => "ارغنداب"],
                ["code" => "" , "province_id" => "27", "district_en"=> "DAMAN", "district_dr"=> "دامان", "district_ps" => "دامان"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PANJWAYEE", "district_dr"=> "پنجوائی", "district_ps" => "پنجوائی"],
                ["code" => "" , "province_id" => "27", "district_en"=> "ZHIRE", "district_dr"=> "ژیری", "district_ps" => "ژیری"],
                ["code" => "" , "province_id" => "27", "district_en"=> "SHAH WALI KOT", "district_dr"=> "شاه ولی کوت", "district_ps" => "شاه ولی کوت"],
                ["code" => "" , "province_id" => "27", "district_en"=> "KHAKREZ", "district_dr"=> "خاکریز", "district_ps" => "خاکریز"],
                ["code" => "" , "province_id" => "27", "district_en"=> "ARGHISTAN", "district_dr"=> "ارغستان", "district_ps" => "ارغستان"],
                ["code" => "" , "province_id" => "27", "district_en"=> "GHORAK", "district_dr"=> "غورک", "district_ps" => "غورک"],
                ["code" => "" , "province_id" => "27", "district_en"=> "MAIWAND", "district_dr"=> "میوند", "district_ps" => "میوند"],
                ["code" => "" , "province_id" => "27", "district_en"=> "SPIN BOLDAK", "district_dr"=> "سپین بولدک", "district_ps" => "سپین بولدک"],
                ["code" => "" , "province_id" => "27", "district_en"=> "NESH", "district_dr"=> "نیش", "district_ps" => "نیش"],
                ["code" => "" , "province_id" => "27", "district_en"=> "MIYANESHIN", "district_dr"=> "میانشین", "district_ps" => "میانشین"],
                ["code" => "" , "province_id" => "27", "district_en"=> "SHORABAK", "district_dr"=> "شورابک", "district_ps" => "شورابک"],
                ["code" => "" , "province_id" => "27", "district_en"=> "MARUF", "district_dr"=> "معروف", "district_ps" => "معروف"],
                ["code" => "" , "province_id" => "27", "district_en"=> "REG (SHIGA)", "district_dr"=> "ریگ(شگه)", "district_ps" => "ریگ(شگه)"],
                ["code" => "" , "province_id" => "27", "district_en"=> "Dand", "district_dr"=> "دند", "district_ps" => "دند"],
                ["code" => "" , "province_id" => "27", "district_en"=> "TAKHTA PUL", "district_dr"=> "تخته پل", "district_ps" => "تخته پل"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 5", "district_dr"=> "ناحیه 5", "district_ps" => "ناحیه 5"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 6", "district_dr"=> "ناحیه 6", "district_ps" => "ناحیه 6"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 7", "district_dr"=> "ناحیه 7", "district_ps" => "ناحیه 7"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 8", "district_dr"=> "ناحیه 8", "district_ps" => "ناحیه 8"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 9", "district_dr"=> "ناحیه 9", "district_ps" => "ناحیه 9"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 10", "district_dr"=> "ناحیه 10", "district_ps" => "ناحیه 10"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 11", "district_dr"=> "ناحیه 11", "district_ps" => "ناحیه 11"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 12", "district_dr"=> "ناحیه 12", "district_ps" => "ناحیه 12"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 13", "district_dr"=> "ناحیه 13", "district_ps" => "ناحیه 13"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 14", "district_dr"=> "ناحیه 14", "district_ps" => "ناحیه 14"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 15", "district_dr"=> "ناحیه 15", "district_ps" => "ناحیه 15"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 16", "district_dr"=> "ناحیه 16", "district_ps" => "ناحیه 16"],
                ["code" => "" , "province_id" => "27", "district_en"=> "PD 17", "district_dr"=> "ناحیه 17", "district_ps" => "ناحیه 17"],
                ["code" => "" , "province_id" => "27", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "28", "district_en"=> "(Capital) SHEBERGHAN", "district_dr"=> "مرکز(شبرغان)", "district_ps" => "مرکز(شبرغان)"],
                ["code" => "" , "province_id" => "28", "district_en"=> "KHWAJA DUKOH", "district_dr"=> "خواجه دوکوه", "district_ps" => "خواجه دوکوه"],
                ["code" => "" , "province_id" => "28", "district_en"=> "KHANAQA", "district_dr"=> "خانقاً", "district_ps" => "خانقاً"],
                ["code" => "" , "province_id" => "28", "district_en"=> "MINGAJIK", "district_dr"=> "منگجیک", "district_ps" => "منگجیک"],
                ["code" => "" , "province_id" => "28", "district_en"=> "QUSH TEPA", "district_dr"=> "قوش تیپه", "district_ps" => "قوش تیپه"],
                ["code" => "" , "province_id" => "28", "district_en"=> "KHAMYAB", "district_dr"=> "خم آب", "district_ps" => "خم آب"],
                ["code" => "" , "province_id" => "28", "district_en"=> "AQCHAH", "district_dr"=> "آقچه", "district_ps" => "آقچه"],
                ["code" => "" , "province_id" => "28", "district_en"=> "FAIZABAD", "district_dr"=> "فیض آباد", "district_ps" => "فیض آباد"],
                ["code" => "" , "province_id" => "28", "district_en"=> "MARDYAN", "district_dr"=> "مردیان", "district_ps" => "مردیان"],
                ["code" => "" , "province_id" => "28", "district_en"=> "QARQIN", "district_dr"=> "قرقین", "district_ps" => "قرقین"],
                ["code" => "" , "province_id" => "28", "district_en"=> "DARZAB", "district_dr"=> "درز آب", "district_ps" => "درز آب"],
                ["code" => "" , "province_id" => "28", "district_en"=> "PD 1 ", "district_dr"=> "ناحیه 1 ", "district_ps" => "ناحیه 1 "],
                ["code" => "" , "province_id" => "28", "district_en"=> "PD 2 ", "district_dr"=> "ناحیه 2 ", "district_ps" => "ناحیه 2 "],
                ["code" => "" , "province_id" => "28", "district_en"=> "PD 3 ", "district_dr"=> "ناحیه 3 ", "district_ps" => "ناحیه 3 "],
                ["code" => "" , "province_id" => "28", "district_en"=> "PD 4 ", "district_dr"=> "ناحیه 4 ", "district_ps" => "ناحیه 4 "],
                ["code" => "" , "province_id" => "28", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "29", "district_en"=> "(Capital) MAYMANA", "district_dr"=> "مرکز(میمنه)", "district_ps" => "مرکز(میمنه)"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PASHTUN KOT", "district_dr"=> "پشتون کوت", "district_ps" => "پشتون کوت"],
                ["code" => "" , "province_id" => "29", "district_en"=> "KHWAJA SABZ POSH-E-WALI", "district_dr"=> "خواجه سبز پوش ولی", "district_ps" => "خواجه سبز پوش ولی"],
                ["code" => "" , "province_id" => "29", "district_en"=> "ALMAR", "district_dr"=> "المار", "district_ps" => "المار"],
                ["code" => "" , "province_id" => "29", "district_en"=> "BIL CHIRAGH", "district_dr"=> "بل چراغ", "district_ps" => "بل چراغ"],
                ["code" => "" , "province_id" => "29", "district_en"=> "SHIRIN TAGAB", "district_dr"=> "شرین تگاب", "district_ps" => "شرین تگاب"],
                ["code" => "" , "province_id" => "29", "district_en"=> "QAISAR", "district_dr"=> "قیصار", "district_ps" => "قیصار"],
                ["code" => "" , "province_id" => "29", "district_en"=> "GURZIWAN", "district_dr"=> "گرزیوان", "district_ps" => "گرزیوان"],
                ["code" => "" , "province_id" => "29", "district_en"=> "DAWLAT ABAD", "district_dr"=> "دولت آباد", "district_ps" => "دولت آباد"],
                ["code" => "" , "province_id" => "29", "district_en"=> "KOHISTAN", "district_dr"=> "کوهستان", "district_ps" => "کوهستان"],
                ["code" => "" , "province_id" => "29", "district_en"=> "QARAM QOLE", "district_dr"=> "قرمقول", "district_ps" => "قرمقول"],
                ["code" => "" , "province_id" => "29", "district_en"=> "QURGHAN", "district_dr"=> "قرغان", "district_ps" => "قرغان"],
                ["code" => "" , "province_id" => "29", "district_en"=> "ANDKHOY", "district_dr"=> "اندخوی", "district_ps" => "اندخوی"],
                ["code" => "" , "province_id" => "29", "district_en"=> "KHAN CHARBAGH", "district_dr"=> "خان چارباغ", "district_ps" => "خان چارباغ"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 5", "district_dr"=> "ناحیه 5", "district_ps" => "ناحیه 5"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 6", "district_dr"=> "ناحیه 6", "district_ps" => "ناحیه 6"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 7", "district_dr"=> "ناحیه 7", "district_ps" => "ناحیه 7"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 8", "district_dr"=> "ناحیه 8", "district_ps" => "ناحیه 8"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 9", "district_dr"=> "ناحیه 9", "district_ps" => "ناحیه 9"],
                ["code" => "" , "province_id" => "29", "district_en"=> "PD 10", "district_dr"=> "ناحیه 10", "district_ps" => "ناحیه 10"],
                ["code" => "" , "province_id" => "29", "district_en"=> "GHORMACH", "district_dr"=> "غورماچ", "district_ps" => "غورماچ"],
                ["code" => "" , "province_id" => "29", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نا معلوم"],
                ["code" => "" , "province_id" => "30", "district_en"=> "(Capital) LASHKARGAH", "district_dr"=> "مرکز(لشکرگاه)", "district_ps" => "مرکز(لشکرگاه)"],
                ["code" => "" , "province_id" => "30", "district_en"=> "NAD ALI", "district_dr"=> "نادعلی", "district_ps" => "نادعلی"],
                ["code" => "" , "province_id" => "30", "district_en"=> "NAWA-I- BARIKZAYEE", "district_dr"=> "نـاوه بـارکـزائـی", "district_ps" => "نـاوه بـارکـزائـی"],
                ["code" => "" , "province_id" => "30", "district_en"=> " NAHER-I- SARAJ", "district_dr"=> "نـهـر ســراج", "district_ps" => "نـهـر ســراج"],
                ["code" => "" , "province_id" => "30", "district_en"=> "WASHER", "district_dr"=> "واشـــیــر", "district_ps" => "واشـــیــر"],
                ["code" => "" , "province_id" => "30", "district_en"=> "GARM SER", "district_dr"=> "گرم سیر", "district_ps" => "گرم سیر"],
                ["code" => "" , "province_id" => "30", "district_en"=> "NAWZAD", "district_dr"=> "نوزاد", "district_ps" => "نوزاد"],
                ["code" => "" , "province_id" => "30", "district_en"=> "SANGIN QALA", "district_dr"=> "سنگـیــن قـلــعه", "district_ps" => "سنگـیــن قـلــعه"],
                ["code" => "" , "province_id" => "30", "district_en"=> "MUSA QALA", "district_dr"=> "مــوســی قـلــعـه", "district_ps" => "مــوســی قـلــعـه"],
                ["code" => "" , "province_id" => "30", "district_en"=> "KAJAKI", "district_dr"=> "کجکی", "district_ps" => "کجکی"],
                ["code" => "" , "province_id" => "30", "district_en"=> "REG-E-KHAN NISHIN", "district_dr"=> "ریـک خـانـشــیـن", "district_ps" => "ریـک خـانـشــیـن"],
                ["code" => "" , "province_id" => "30", "district_en"=> "BAGHRAN", "district_dr"=> "باغران", "district_ps" => "باغران"],
                ["code" => "" , "province_id" => "30", "district_en"=> "DESHU", "district_dr"=> "دیشو", "district_ps" => "دیشو"],
                ["code" => "" , "province_id" => "30", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "30", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "30", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "30", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "30", "district_en"=> "Garashk", "district_dr"=> "گرشک", "district_ps" => "گرشک"],
                ["code" => "" , "province_id" => "29", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نا معلوم"],
                ["code" => "" , "province_id" => "30", "district_en"=> "Maarja", "district_dr"=> "مارجه", "district_ps" => "مارجه"],
                ["code" => "" , "province_id" => "30", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "31", "district_en"=> "(Capital) QALA-E-NOW", "district_dr"=> "مرکز(قلعه نو)", "district_ps" => "مرکز(قلعه نو)"],
                ["code" => "" , "province_id" => "31", "district_en"=> "AB KAMARI", "district_dr"=> "آبکمــری", "district_ps" => "آبکمــری"],
                ["code" => "" , "province_id" => "31", "district_en"=> "MUQUR", "district_dr"=> "مقـــر", "district_ps" => "مقـــر"],
                ["code" => "" , "province_id" => "31", "district_en"=> "QADIS", "district_dr"=> "قادس", "district_ps" => "قادس"],
                ["code" => "" , "province_id" => "31", "district_en"=> "BALA MURGHAB", "district_dr"=> "بالامــرغــاب", "district_ps" => "بالامــرغــاب"],
                ["code" => "" , "province_id" => "31", "district_en"=> "JAWAND", "district_dr"=> "جونـد", "district_ps" => "جونـد"],
                ["code" => "" , "province_id" => "31", "district_en"=> "GHORMACH", "district_dr"=> "غـورمــاچ", "district_ps" => "غـورمــاچ"],
                ["code" => "" , "province_id" => "31", "district_en"=> "Unknown ", "district_dr"=> "نامعلوم ", "district_ps" => "نامعلوم "],
                ["code" => "" , "province_id" => "32", "district_en"=> "(Capital) Herat", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "32", "district_en"=> "ENJIL", "district_dr"=> "انجیل", "district_ps" => "انجیل"],
                ["code" => "" , "province_id" => "32", "district_en"=> "NIZAM-E-SHAHID (GUZARA)", "district_dr"=> "(نظام شهید) گذره", "district_ps" => "(نظام شهید) گذره"],
                ["code" => "" , "province_id" => "32", "district_en"=> "KARRUKH", "district_dr"=> "کرخ", "district_ps" => "کرخ"],
                ["code" => "" , "province_id" => "32", "district_en"=> "ZENDAJAN", "district_dr"=> "زنده جان", "district_ps" => "زنده جان"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PASHTUN ZARGHUN", "district_dr"=> "پشتون زرغون", "district_ps" => "پشتون زرغون"],
                ["code" => "" , "province_id" => "32", "district_en"=> "KUSHK (RUBAT-E-SANGI)", "district_dr"=> "(کشک) رباط سنگی", "district_ps" => "(کشک) رباط سنگی"],
                ["code" => "" , "province_id" => "32", "district_en"=> "GULRAN", "district_dr"=> "گلران", "district_ps" => "گلران"],
                ["code" => "" , "province_id" => "32", "district_en"=> "ADRASKAN", "district_dr"=> "ادرسکن", "district_ps" => "ادرسکن"],
                ["code" => "" , "province_id" => "32", "district_en"=> "KUSHK-E-KOHNA", "district_dr"=> "کشک کهنه", "district_ps" => "کشک کهنه"],
                ["code" => "" , "province_id" => "32", "district_en"=> "GHORYAN", "district_dr"=> "غوریان", "district_ps" => "غوریان"],
                ["code" => "" , "province_id" => "32", "district_en"=> "OBE", "district_dr"=> "اوبه", "district_ps" => "اوبه"],
                ["code" => "" , "province_id" => "32", "district_en"=> "KOHSAN", "district_dr"=> "کهسان", "district_ps" => "کهسان"],
                ["code" => "" , "province_id" => "32", "district_en"=> "SHINDAND", "district_dr"=> "شیندند", "district_ps" => "شیندند"],
                ["code" => "" , "province_id" => "32", "district_en"=> "FERSI", "district_dr"=> "فرسی", "district_ps" => "فرسی"],
                ["code" => "" , "province_id" => "32", "district_en"=> "CHISHT-E-SHARIF", "district_dr"=> "چشت شریف", "district_ps" => "چشت شریف"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 1", "district_dr"=> "ناحیه1", "district_ps" => "ناحیه1"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 2", "district_dr"=> "ناحیه2 ", "district_ps" => "ناحیه2 "],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 3", "district_dr"=> "ناحیه3", "district_ps" => "ناحیه3"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 4", "district_dr"=> "ناحیه4", "district_ps" => "ناحیه4"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 5", "district_dr"=> "ناحیه5", "district_ps" => "ناحیه5"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 6", "district_dr"=> "ناحیه6", "district_ps" => "ناحیه6"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 7", "district_dr"=> "ناحیه7", "district_ps" => "ناحیه7"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 8", "district_dr"=> "ناحیه8", "district_ps" => "ناحیه8"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 9", "district_dr"=> "ناحیه9", "district_ps" => "ناحیه9"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 10", "district_dr"=> "ناحیه10", "district_ps" => "ناحیه10"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 11", "district_dr"=> "ناحیه11", "district_ps" => "ناحیه11"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 12", "district_dr"=> "ناحیه12", "district_ps" => "ناحیه12"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PD 13", "district_dr"=> "ناحیه13", "district_ps" => "ناحیه13"],
                ["code" => "" , "province_id" => "32", "district_en"=> "PUSHT KOH", "district_dr"=> "پشت کوه", "district_ps" => "پشت کوه"],
                ["code" => "" , "province_id" => "32", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "33", "district_en"=> "(Capital) FARAH", "district_dr"=> "مرکز", "district_ps" => "مرکز"],
                ["code" => "" , "province_id" => "33", "district_en"=> "PUSHTRUD", "district_dr"=> "پشت رود", "district_ps" => "پشت رود"],
                ["code" => "" , "province_id" => "33", "district_en"=> "KHAK-E-SAFED", "district_dr"=> "خاک سفید", "district_ps" => "خاک سفید"],
                ["code" => "" , "province_id" => "33", "district_en"=> "QALA-E-KAH", "district_dr"=> "قلعه کاه", "district_ps" => "قلعه کاه"],
                ["code" => "" , "province_id" => "33", "district_en"=> "SHIB KOH", "district_dr"=> "شیب کوه", "district_ps" => "شیب کوه"],
                ["code" => "" , "province_id" => "33", "district_en"=> "BALA BULUK", "district_dr"=> "بالا بلوک", "district_ps" => "بالا بلوک"],
                ["code" => "" , "province_id" => "33", "district_en"=> "ANAR DARA", "district_dr"=> "اناردره", "district_ps" => "اناردره"],
                ["code" => "" , "province_id" => "33", "district_en"=> "BAKWA", "district_dr"=> "بکواه", "district_ps" => "بکواه"],
                ["code" => "" , "province_id" => "33", "district_en"=> "LASH-E-JUWAYN", "district_dr"=> "لاش جوین", "district_ps" => "لاش جوین"],
                ["code" => "" , "province_id" => "33", "district_en"=> "GULISTAN", "district_dr"=> "گلستان", "district_ps" => "گلستان"],
                ["code" => "" , "province_id" => "33", "district_en"=> "PUR CHAMAN", "district_dr"=> "پرچمن", "district_ps" => "پرچمن"],
                ["code" => "" , "province_id" => "33", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "33", "district_en"=> "PD 2", "district_dr"=> "ناحیه 2", "district_ps" => "ناحیه 2"],
                ["code" => "" , "province_id" => "33", "district_en"=> "PD 3", "district_dr"=> "ناحیه 3", "district_ps" => "ناحیه 3"],
                ["code" => "" , "province_id" => "33", "district_en"=> "PD 4", "district_dr"=> "ناحیه 4", "district_ps" => "ناحیه 4"],
                ["code" => "" , "province_id" => "33", "district_en"=> "UNKNOWN", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
                ["code" => "" , "province_id" => "34", "district_en"=> "(Capital) ZARANJ", "district_dr"=> "مرکز(زرنج)", "district_ps" => "مرکز(زرنج)"],
                ["code" => "" , "province_id" => "34", "district_en"=> "KANG", "district_dr"=> "کنگ", "district_ps" => "کنگ"],
                ["code" => "" , "province_id" => "34", "district_en"=> "ASL-E-CHAKHANSUR", "district_dr"=> "اصل چخانسور", "district_ps" => "اصل چخانسور"],
                ["code" => "" , "province_id" => "34", "district_en"=> "CHAR BURJAK", "district_dr"=> "چهاربرجک", "district_ps" => "چهاربرجک"],
                ["code" => "" , "province_id" => "34", "district_en"=> "KHASHROD", "district_dr"=> "خاشرود", "district_ps" => "خاشرود"],
                ["code" => "" , "province_id" => "34", "district_en"=> "PD 1", "district_dr"=> "ناحیه 1", "district_ps" => "ناحیه 1"],
                ["code" => "" , "province_id" => "34", "district_en"=> "Delaram", "district_dr"=> "دلارام ", "district_ps" => ""],
                ["code" => "" , "province_id" => "34", "district_en"=> "Unknown", "district_dr"=> "نامعلوم", "district_ps" => "نامعلوم"],
            ];

        foreach ($districts as $district)
            District::create($district);
    }
}
