// src/locales/dari.js
const dari = {
    welcomeMessage: "به سیستم مدیریت ترمینل باربری حیرتان خوش آمدید",
    weight: "وزن",
  
    createdLoads: "بارهای ثبت شده",
    plateType: "نوعیت پلیت",
    vehicleWeight: "وزن(تن) واسطه",
    vehicleMaxCapacity: "ظرفیت واسطه(تن)",
    description: "توضیحات",
    loadCatagories: "کتگوری بار",
    loadType: "نوعیت بار",
    NewLoads: "بار جدید",
    dashboard: "داشبورد",
    setting: "بخش ثبت",
    outDoor: "دروازه خروجی",
    inDoor: "دروازه دخولی",
    reports: "راپورها",
    users: "کاربران",
    profile: "اکونت",
    usersList: "لیست کاربران",
    userType: "نوعیت کاربر",
    vehiclesTypes: "نوعیت وسایط",
    vehiclesOwners: "مالکین وسایط",
    drivers: "راننده گان",
    companies: "شرکت ها",
    terminals: "ترمینل ها",
    terminal: "ترمینل",
    routes: "مسیرها",
    route: "مسیر",
    relatedRoutes: "مسیرهای مرتبط",
    routeNotFound: "هیچ مسیری وجود ندارد",
    vehicleStatus: "حالت واسطه",
    allProvinces: "همه ولایت ها",
    tarrifPaymentStatus: "وضعیت پرداخت تعرفه",
    transportation_fee: "ترانسپورتی حق الخدمت",
  queueList: "لیست وسایط دخولی",
    fare: "کرایه",
    fareEdit: "تغیر دادن کرایه",
    bandars: "بنادر کنترولی",
    status: "حالت",
    action: "عملیات",
    save: "ذخیره کردن",
    saving: "در حال ذخیره ...",
    NO: "شماره",
    disable: "غیر فعال کردن",
    approved: "تایید شده",
    approve: "تایید ",
    notApproved: "تایید نشده",
    editInfo: "اصلاح نمودن ",
    reNew: "تمدید کردن",
    update: "ثبت تغییرات",
    updating: "در حال ثبت تغییرات ...",
    goBack: "برگشت",
    search: "جستجو",
    searchByName: "جستجو به اساس نام",
    search_by_name_or_id: "جستجو بر اساس نام یا شماره تذکره",
    search_driver: "جستجو موټر وان",
    search_owner: "جستجو مالک",
    searching: "در حال جستجو ...",
    profile: "اکونت",
    editProfile: "اصلاح نمودن اکونت",
    pashto: "پښتو",
    persion: "فارسی",
    login: "ورود به سیستم",
    loginToYourAcount: "به اکونت خود داخل شوید",
    welcomBack: "به سیستم مدیریت ترمینل باربری حیرتان خوش آمدید",

    rememberMe: "پسورد ما را فراموش نکنید",
    forgotPassword: "پسورد خود را فراموش کرده اید؟",
    logout: "خارج شدن از سیستم",
    loggingOut: "خارج شدن از سیستم ...",
    vehiclesTypesList: "لیست نوعیت وسایط",
    vehicleType: "نوعیت واسطه",
    vehileCompany: "شرکت واسطه",
    addnewVehicleType: "اضافه نمودن نوعیت واسطه جدید",
    vehicleCapacity: "ظرفیت واسطه",
    newType: "نوعیت جدید",
    addVehicleType: "اضافه نمودن نوعیت واسطه",
    editVehicleType: "اصلاح نمودن نوعیت واسطه",
    storedSuccessfully: "معلومات موفقانه ذخیره ګردید",
    updatedSuccessfully: "معلومات موفقانه تغییر ګردید",
    renewedSuccessfully: "معلومات موفقانه تمدید ګردید",
    upprovedSuccessfully: "معلومات موفقانه تایید ګردید",
    disabledSuccessfully: "معلومات موفقانه مسترد ګردید",
    approveInfo: "تایید نمودن معلومات",
    areYouSure: "آیا شما مطمئن هستید ؟",
    yesChange: "بلی، تایید شود",
    cancel: "لغوه",
    close: "بستن",
    changeStatus: "تغییر دادن حالت",
    areYouSureToChangeStatus: "ایا شما مطمئن هستید تا حالت را مسترد نمایید",
    unApproved: "معلومات مسترد ګردید",
    vehicleOwnersList: "لسیت مالکین وسایط",
    name: "نام",
    fatherName: "نام پدر",
    nationalID: "نمبر تذکره",
    phoneNO: "شماره تلیفون",
    image: "تصویر",
    vehicleOwnerImage: "تصویر مالک واسطه",
    documents: "اسناد",
    newOwner: "مالک جدید",
    addVehicleOwner: "اضافه نمودن مالک جدید",
    selectImage: "انتخاب تصویر",
    selectDocument: "انتخاب اسناد",
    changeVehicleOwnerInfo: "اصلاح نمودن معلومات مالک واسطه",
    driversList: "لسیت درایورها",
    newDriver: "موتروان جدید",
    editDriver: "اصلاح نمودن موتروان",
    addNewDriver: "اضافه نمودن درایور جدید",
    changeDriverInfo: "تغییر نمودن معلومات درایور",
    driverImage: "عکس موتروان",
    is_driver_owner_too: "آیا موتروان هم مالک است؟",
    is_owner_driver_too: "آیا مالک هم موتروان است؟",
    yes_also_driver: "بلی، مالک هم موتروان است",
    yes_also_owner: "بلی، موتروان هم مالک است",
    companiesList: "لیست شرکت ها",
    expiredLisenses: "جواز های انقضاء",
    companyName: "نام شرکت",
    TIN: "نمبر TIN",
    lisenseStartDate: "تاریخ شروع جواز",
    lisenseEndDate: "تاریخ انقضاء جواز",
    lisenceNumber: "نمبر جواز",
    newCompany: "شرکت جدید",
    addNewCompany: "اضافه نمودن شرکت جدید",
    changeCompanyInfo: "تغییر دادن معلومات شرکت",
    vehicles: "وسایط",
    percentage: "فیصدي",
    additionalFee: "قیس اضافی",

    branches: "نماینده گی ها",
    companyBranches: "نماینده ګی های شرکت",
    addBranch: "اضافه نمودن نماینده ګی",
    addBranchToCompany: "اضافه نمودن نماینده ګی به شرکت",
    activityTypes: "نوعیت فعالیت",
    companyLisenceExpired: "تاریخ جواز شرکت ختم ګریده است",
    plateShaciEngineNO: "پلیټ، شاسي یا انجن نمبر واسطه را اینجا وارد کنید",
    licenseScanFile: "فایل اسکن جواز",
    newqueue: "ثبت نوبت جدید",
    companyVehiclesList: "لیست وسایط ثبت شده",
    viewHistory: "مشاهده تاریخچه",
    plateNO: "نمبر پلیت",
    engineNO: "انجن نمبر",
    shaciNO: "شاسی نمبر",
    vehicleModal: "مادل واسطه",
    vehicleColor: "رنگ واسطه",
    vehicleOwner: "مالک واسطه",
    editOwner: " اصلاح نمودن مالک",
    newVehicle: "ثبت واسطه جدید",
    addNewVehicle: "اضافه نمودن واسطه جدید",
    plateGrade: "درجه پلیت",
    selectGrade: "درجه را انتخاب نمایید",
    plateProvince: "ولایت پلیت",
    selectProvince: "ولایت را انتخاب نمایید",
    selectTerminal: "ترمینل را انتخاب نمایید",
    selectDistrict: "ولسوالی را انتخاب نمایید",
    vehicleDriver: "موتروان واسطه",
    vehicleImage: "تصویر واسطه",
    changeVehicleInfo: "تغییر معلومات واسطه",
    changeVehicleCompany: "تغییر شرکت واسطه",
    deActive: "غیر فعال کردن",
    noResultFound: "کدام نتیجه پیدا نګردید",

    companyBranchesList: "لیست نماینده گی ها شرکت {{name}}",
    province: "ولایت",
    descriptions: "توضیحات",
    newBranch: "نماینده گی جدید",
    addNewBranch: "اضافه نمودن نماینده گی جدید",
    changeBranch: "تغییر دادن نماینده گی",

    companyActivityTypeList: "لیست نوعیت فعالیت شرکت",
    newActivity: "فعالیت جدید",
    addNewActivityType: "اضافه نمودن فعالت جدید",
    changeActivityType: "تغییر دادن فعالیت",
    activityType: "نوعیت فعالیت",

    terminalsList: "لیست ترمینل ها",
    terminalName: "نام ترمینل",
    location: "موقعیت",
    newTerminal: "ترمینل جدید",
    addNewTerminal: "اضافه نمودن ترمینل جدید",
    changeTerminalInfo: "تغییر نمودن معلومات ترمینل",

    routesList: "لسیت مسیرها",
    newRoute: "مسیر جدید",
    addNewRoute: "اضافه نمودن مسیر جدید",
    startingProvince: "ولایت شروع",
    endingProvince: "ولایت ختم",
    startingDistrict: "ولسوالي شروع",
    endingDistrict: "ولسوالي ختم",
    changeRouteInfo: "تغییر دادن معلومات مسیر",

    fareList: "لیست کرایه",
    startDate: "تاریخ شروع",
    newFare: "کرایه جدید",
    editFare: "اصلاح نمودن کرایه",
    addNewFare: "اضافه نمودن کرایه جدید",
    changeFareInfo: "تغییر معلومات کرایه",
    selectRoute: "مسیر را انتخاب نمایید",
    selectVehicleType: "نوعیت واسطه را انتخاب نمایید",

    bandarsList: "لیست بنادر",
    bandarName: "نام بندر",
    newBandar: "بندر جدید",
    editBandar: "تغیر دادن بندر",
    addNewBandar: "اضافه نمودن بندر جدید",
    changeBandarInfo: "تغییر دادن معلومات بندر",
    allTypes: "همه نوعیت ها",
    smallVehicles: "وسایط خورد ظرف",
    addSmallVehicle: "اضافه نمودن وسایط خورد ظرف",
    editSmallVehicle: "اصلاح نمودن وسایط خورد ظرف",
    vehicleRoutes: "مسیر های واسطه",
    addCompany: "اضافه نمودن شرکت",
    SearchYourDesiredVehicle: "واسطه مورد نظر خود را اینجا جستجو کنید",
    vehicleCatagory: "کتګوری وسایط",
    largeVehicles: "وسایط ثبت شده",
    outgoingVehiclesList: "لیست وسایط خروجی",
    queueHead: "لیست وسایط دخولی ترمینل",
    todayOutgoingVehicles: "وسایط خارج شده امروزه",
    company: "شرکت",
    addVehicleToCompany: "اضافه کردن موتر به {{company}}",
    outDate: "تاریخ خروج",
    outTime: "وقت خروج",
    date: "تاریخ",
    queueDashboard: "تنظیم نوبت",
    newOutgoingVehicle: "واسطه خروجی جدید",
    addNewOutgoingVehicle: "اضافه نمودن واسطه خروجی جدید 🚙",
    addNewQueue: "اضافه نمودن نوبت جدید",
    enterOutgoingVehicleShaciNO: "شاسی نمبر واسطه را داخل نمایید",
    chalanNO: "نمبر چالان",
    queueType: "نوعیت قطار نوبت",
    queueConfiguration: "تنظیمات قطار نوبت",
    destinationProvince: "ولایت انتقال بار",
    helper: "کمکی",
    DateIn: "تاریخ ورود",
    queueCatagoryHead: "لیست وسایط در قطار نوبت  --  {{name}}",
    rented: "دربست شده",
    outgoingVehicleType: "نوعیت واسطه خروجی",
    normal: "عادی",
    damagedVehiclePlateNO: "پلیت نمبر واسطه خراب شده",
    viewDetails: "مشاهده معلومات",
    details: "جزئیات",
    total: "مجموعی",
    totalvehicles: "تمام وسایط",
    routeFareNotDefined: "کرایه مسیر هنوز مشحص نگردیده",
    routeFare: "کرایه مسیر",
    printToken: "پرینت نمودن توکن",
    veiwDetails: "مشاهده جزئیات",
    outedVehicleDetails: "جزئیات واسطه خارج شده",
    from: "از",
    to: "به",
    passengersInfo: "معلومات مسافرین",
    passengersNO: "تعداد مسافرین",
    movementDate: "تاریخ حرکت",
    movementTime: "وقت حرکت",
    vehicleInfo: "معلومات واسطه",
    waiting: "در حال انتظار...",
    reject: "رد کردن",
    rejected: "رد شده",
    rejectReason: "دلیل رد",
    makeDamage: "خراب کردن",
    damageReason: "علت رد نمودن",
    damaged: "خراب شده",
    print: "پرینت نمودن",
    terminalInfo: "جزئیات ترمینل",
    damageIsPossibleIn24H: "خراب شدن در ۲۴ ساعت امکان پذیر است",
    imageNotAvailable: "تصویر موجود نمی باشد",
    branchNotAvailable: "نماینده ګی موجود نمی باشد",
    last30DaysIncome: "درآمد ۳۰ روز ګذشته",

    outedVehicles‌basedOnTerminal: "وسایط خارج شده به اساس ترمینل",
    outedvehileReportBasedOnPalate: " وسایط خارج شده به اساس پلیت",
    largeOutedVehiclesReportsBasdOnCompany: " وسایط خارج شده بزرګ به اساس شرکت",
    endDate: "تاریخ ختم",
    reportType: "نوعیت راپور",
    totalReport: "راپور اجمالي",
    descriptiveReport: "راپور تفصیلی",
    generateReport: "ګرفتن راپور",
    generatingReport: "ګرفتن راپور...",
    terminalLocation: "موقعیت ترمینل",
    branch: "نماینده ګی",
    farePerPerson: "کرایه فی نفر",
    totalFare: "مجموعی حق الخدمت ترانسپورتی",
    transportationFee: "حق الخدمت ترانسپورتی",
    totalTransportationFee: "مجموع حق الخدمت ترانسپورتی",
    selectCompany: "شرکت را انتخاب نمایید",
    vehiclesNO: "تعداد واسطه",
    bandarStatus: "حالت بندر",
    checkTime: "وقت چیک",
    checkBandar: "بندر چیک کننده",
    checker: "چیک کننده",
    checkBandar: "بندر چیک کننده",
    bandarStatus: "حالت در بندر",
    roles: "صلاحیت ها",
    newUser: "کاربر جدید",
    email: "ایمیل آدرس",
    role: "صلاحیت",
    type: "نوعیت",
    addNewUser: "اضافه نمودن کاربر جدید",
    password: "پسورد عبور",
    confirmPassword: "پسورد خود را تایید کنید",
    changeUserInfo: "تغییر نمودن معلومات کاربر",
    checked: "بررسی شده",
    notChecked: "بررسی نشده",
    addNewVehicle: "اضافه نمودن واسطه جدید",
    newRole: "صلاحیت/ رول جدید",
    addNewRole: "اضافه نمودن صلاحیت/ رول جدید",
    editRole: "اصلاح نمودن صلاحیت/ رول",
    roleName: "نام رول",
    changeRoleInfo: "تغییر نمودن معلومات صلاحیت/ رول",
    rolesList: "لیست صلاحیت ها",
    permissions: "صلاحیت ها",
    enterEmailHere: " ایمیل آدرس را تایپ کنید",
    enterPasswordHere: "پاسورد را تایپ کنید",
    systemColor: "رنګ سیستم",
    systemLanguage: "زبان سیستم",
    openUserMenu: "باز کردن مینو کاربر",
    vehicleList: "لیست وسایط",
    summary: "خلاصه",
    monthlyRevenue: "عواید ماهانه",
    largeVehiclesRevenueGraph: "گراف عواید وسایط بزرگ ",
    transportationCompanies: "شرکت های ترانسپورتی",
    figuresBasedCharts: "ارقام به اساس چارت ها ",
    revenueStatisticsSystem: "سیستم احصایه و عواید وسایط مسافربری",
    actionInSystem: "فعالیت در سیستم",
    grade: "رتبه",
    scores: "نمرات",
    figures: "ارقام",
    companyType: "نوعیت شرکت",
    LoadsList: "لیست بارها",
    vehicleTypeIsNeeded: "مشخص نمودن نوعیت واسطه ضروری میباشد",
    vehicleCapacityIsNeeded: "مشخص نمودن ظرفیت واسطه ضروری میباشد",
    nameIsNeeded: "نام ضروری میباشد",
    fatherNameIsNeeded: "نام پدر ضروری میباشد ",
    phoneNOIsNeeded: "شماره تلیفون ضروری میباشد",
    nationIDIsNeeded: "نمبر تذکره ضروری میباشد",
    documentIsNeeded: "اسناد ضروری میباشد",
    imageIsNeeded: "تصویر ضروری میباشد",
    phoneNOShouldBeValid: "شماره تلیفون باید یک شماره معتبر باشد",
    maxFileSize300: "حجم فایل باید از ۳۰۰ زیاد نباشد",
    documentIsNeeded: "اسناد ضروری میباشد",
    unvaliedFileType: "نوع فایل نامعتبر است",
    pdfIsAllowed: "فایل باید فارمت pdf را داشته باشد",
    companyNameIsNeeded: "نام شرکت ضروری میباشد",
    markaziatIsNeeded: "مرکزیت ضروری میباشد",
    lisenseNumberIsNeeded: "نمبر جواز ضروری میباشد",
    TINIsNeeded: "نمبر TIN ضروری میباشد",
    startDateIsNeeded: "تاریخ شروع ضروری میباشد",
    endDateIsNeeded: "تاریخ انقضاء ضروری میباشد",
    plateNOIsNeeded: "نمبر پلیت ضروری میباشد",
    plageGradeIsNeeded: "درجه پلیت ضروری میباشد",
    provinceIsNeeded: "ولایت ضروری میباشد",
    engineNOIsNeeded: "انجن نمبر ضروری میباشد",
    shaciNOIsNeeded: "شاسی نمبر ضروری میباشد",
    vehicleModalIsNeeded: "مادل وساطه ضروری میباشد",
    vehicleColorIsNeeded: "رنګ واسطه ضروری میباشد",
    terminalNameIsNeeded: "نام ترمینل ضروری میباشد",
    terminalIsNeeded: "ترمینل ضروری میباشد",
    locationIsNeeded: "انتخاب موقعیت ضروری میباشد",
    companyIsNeeded: "انتخاب شرکت ضروری میباشد",
    routIsNeeded: "انتخاب مسیر ضروری میباشد",
    atleastSelectOneRoute: "حد اقل باید یک مسیر را انتخاب نمایید",
    startingProvinceIsNeeded: "ولایت شروع (مبدا) ضروری میباشد",
    endingProvinceIsNeeded: "ولایت ختم (مقصد) ضروری میباشد",
    startingDistrictIsNeeded: "ولسوالي شروع (مبدا) ضروری میباشد",
    endingDistrictIsNeeded: "ولسوالي ختم (مقصد) ضروری میباشد",
    fareIsNeeded: "کرایه ضروری میباشد",
    bandarIsNeeded: "نام بندر ضروری میباشد",
    routeIsNeeded: "انتخاب مسیر ضروری میباشد",
    chalanIsNeeded: "نمبر چالان ضروری میباشد",
    rejectReasonIsNeeded: "دلیل رد ضروری میباشد",
    damageReasonIsNeeded: "دلیل خراب شده ضروری میباشد",
    emailIsInvalid: "ایمیل آدرس غیر معتبر میباشد",
    credentialInvalid: "ایمیل یا پسورد عبور اشتباه است.",
    emailIsNeeded: "ایمیل آدرس ضروری میباشد",
    passwordIsNeeded: "پسورد عبور ضروری میباشد",
    minPasswordShouldBe4NO: "پسورد عبور باید حد اقل ۴ عدد باشد",
    passwordShouldBeSame: "پسورد عبور باید یکسان باشد",
    confirmPasswordIsNeeded: "تایید پسورد عبور ضرور میباشد",
    typeIsNeeded: "نوعیت ضرور میباشد",
    roleIsNeeded: "انتخاب صلاحیت ضروری میباشد",

    undefined: "مشخص نشده",
    reportTypeIsNeeded: "نوعیت راپور ضروری میباشد",
    copyright: "تمام حقوق کاپی محفوظ است. سیستم احصایه و عواید وسایط مسافربری ",
    motaIea: "امارت اسلامی افغانستان. وزارت ترانسپورت و هوانوردی",

    next: "بعدی",
    previous: "قبلی",

    log: "لاګ",

    filterOptions: "گزینه‌های فیلتر برای جستجو",
    selectDistrict: "ولسوالی را انتخاب کنید",
    selectProvince: "ولایت را انتخاب کنید",
    selectCompany: "شرکت را انتخاب کنید",
    selectType: "نوع را انتخاب کنید",
    selectVehicle: "موتر را انتخاب کنید",
    selectDriver: "راننده را انتخاب کنید",
    selectOwner: "مالک را انتخاب کنید",
    selectBandar: "بندر را انتخاب کنید",
    selectBranch: "شعبه را انتخاب کنید",
    selectActivity: "فعالیت را انتخاب کنید",
    selectFare: "کرایه را انتخاب کنید",
    selectTerminal: "ترمینال را انتخاب کنید",
    selectRoute: "مسیر را انتخاب کنید",
    selectVehicleType: "نوع موتر را انتخاب کنید",
    selectVehicleOwner: "مالک موتر را انتخاب کنید",
    selectVehicleDriver: "راننده موتر را انتخاب کنید",
    getReport: "گرفتن راپور",
    loading: "در حال برسی ...",
    passwordNote:
        "نوت: پسورد عبور باید حداقل ۸ حرف داشته باشد و شامل حروف، اعداد و علامت‌های خاص مانند (@، #، $) باشد.",
    hasDocument: "آیا واسطه اسناد دارد؟",
    vehicleListTitle: "لیست وسایط",
    platePlaceholder: "شماره پلیت را وارد کنید",
    chooseCompany: "شرکت را انتخاب کنید",
    chooseType: "نوع وسایط را انتخاب کنید",
    largeVehicle: "وسایط بزرگ",
    smallVehicle: "وسایط خورد",
    vehicleDriver: "راننده وسایط",
    vehicleOwner: "مالک وسایط",
    vehileCompany: "شرکت وسایط",
    changeVehicleCompany: "تغییر شرکت وسایط",

    violations: "تخلفات",
    ownerProvince: "ولایت مالک",
    ownerDistrict: "ولسوالی مالک",
    addingNewVehicle: "اضافه نمودن واسطه جدید",
    ListOfViolatedVehicles: "لیست وسایط متخلف",
    vehicleOwnerDetails: "مشخصات مالک واسطه",
    vehicleOwnerName: "نام مالک واسطه",
    vehicleOwnerFName: "نام پدر مالک واسطه",
    ownerVillage: "قریه مالک",
    errorOccured: "خطا رخ داد، دوباره کوشش نمایید",
    infoNotFound: "معلومات پیدا نشد",
    changeVehicleInfo: "تغییر نمودن مشخصات واسطه",
    arrestDate: "تاریخ گرفتاری",
    freeDate: "تاریخ رهایی",
    violationType: "نوع تخلف",
    arrestPlace: "محل گرفتاری",
    newViolation: "تخلف جدید",
    listOfVehicleViolations: "لیست تخلفات واسطه",
    addingNewViolation: "اضافه نمودن تخلف جدید",
    changingViolationInfo: "تغییر نمودن معلومات تخلف",
    no_approved_vehicle_in_this_terminal:
        "هیچ وسیله نقلیه‌ای در این ترمینال تأیید نشده است.",

    paymentStatusPaid: "این تعرفه موفقانه پرداخت شده است.",
    paymentStatusFailed: "پرداختی برای این تعرفه پیدا نشد.",
    paymentStatusNotPaid: "وضعیت پرداخت تأیید نشد.",
    errorCheckingPaymentStatus: "خطا هنگام بررسی وضعیت پرداخت.",
    tarrifs: "تعرفه ها",
    search: "جستجو",
    searchByPlateNo: "جستجو بر اساس شماره پلیت",
    helpDesk: {
        title: "دفتر کمک",
        titlePlaceholder: "عنوان را وارد کنید",
        descriptionPlaceholder: "مشکل خود را توضیح دهید",
        createTicket: "ایجاد تیکت",
        tickets: "تیکت‌ها",
        by: "توسط",
        replies: "پاسخ‌ها",
        noReplies: "هنوز پاسخی وجود ندارد",
        replyPlaceholder: "پاسخ خود را وارد کنید",
        reply: "پاسخ دهید",
    },
    vehicleDetails: {
        vehicleDetails: "جزئیات واسطه",

        title: "جزئیات وسایط",
        companyName: "نام شرکت",
        licenseNumber: "شماره جواز",
        licenseStart: "تاریخ شروع جواز",
        licenseEnd: "تاریخ ختم جواز",
        description: "توضیحات",
        vehicleType: "نوع وسیله نقلیه",
        plateNo: "شماره پلیت",
        engineNo: "شماره انجن",
        vehicleColor: "رنگ وسیله",
        chassisNo: "شماره شاسی",
        farePerPassenger: "کرایه هر مسافر",
        route: "مسیر",
        outDate: "تاریخ خروج",
        outTime: "وقت خروج",
        passengers: "مسافران",
        ownerName: "نام مالک",
        ownerPhone: "شماره تماس مالک",
        driverName: "نام راننده",
        driverPhone: "شماره تماس راننده",
        terminalName: "نام ترمینال",
        terminalLocation: "موقعیت",
        timeRemaining: "زمان باقی‌مانده برای تأیید",
        hours: "ساعت",
        timeExpired: "زمان تأیید به پایان رسیده است.",
        submitReason: "ارسال دلیل",
        reasonPlaceholder: "دلیل برای رد شدن",
        reject: "رد کردن",
        damage: "خراب کردن",
        approve: "تأیید",
    },
    common: {
        loading: "در حال بارگذاری...",
    },

    accounts: "حسابها",
    companyDetails: "جزئیات شرکت",
    wantToApprove: "آیا میخواهید این را قبول کنید؟",
    pay: "پرداخت کردن",
    checkPayment: "بررسی پرداخت",
    show: "نمایش",
    rejectTarrif: "رد نمودن تعرفه",
    tarrifDescriptions: "جزئیات تعرفه",
    bankReceipt: "رسید بانک (آویز)",
    tarrifArrivalDate: "تاریخ رسید تعرفه",
    totalOutVehicles: "تمام موتر های خارجی",
    tarrifFile: "فایل تعرفه",
    tarrifPayment: "پرداخت تعرفه",
    tarrifsList: "لیست تعرفه ها",
    addNewTarrif: " تعرفه جدید را اضافه کنید",
    tarrifNotPayed: "تعرفه پرداخت نشده است",
    problemInRetreivingData: "در بازیابی معلومات مشکل وجود داشت.",
    rejectedSuccessfully: "موفقانه رد ګردید",
    yesAccept: "بلی قبول شود",
    newTarrif: "تعرفه جدید",
    addingNewTarrif: "اضافه نمودن تعرفه جدید",
    tarrifStartDate: "تاریخ شروع تعرفه",
    tarrifEndDate: "تاریخ ختم تعرفه",
    tarrifNO: "نمبر تعرفه",
    checkTarrifs: "چیک کردن تعرفه ها",
    yes: "بلی",
    no: "نخیر",
    wantToAddViolation: "آیا میخواهید تخلف اضافه کنید؟",
    storeDate: "تاریخ ذخیره",
    lastUpdateDate: " آخرین به‌روزرسانی",
    companiesVehicles: "وسایط شرکت ها",

    tarrifIsRequired: "شماره تعرفه الزامی است",
    tarrifNotFound: "شماره تعرفه یافت نشد",

    tarrifTypes: "نوعیت های تعرفه",
    tarrifsNumber: "تعداد تعرفه ها",
    totalAccounts: "حساب های مجموعی",
    savedTarrifs: "تعرفه های ثبت شده",
    payedTarrifs: "تعرفه های پرداخت شده",
    pendingTarrifs: "تعرفه های در حال انتظار",
    rejectedTarrifs: "تعرفه های رد شده",
    pending: "در حال انتظار",
    saved: "ثبت شده",
    rejected: "رد شده",
    paid: "پرداخت شده",
    processSucceed: "پروسه موفق بود",

    // validation messages for company
    company_name_required: "نام شرکت ضروری است",
    company_name_string: "نام شرکت باید یک رشته باشد",
    company_name_max: "نام شرکت نباید بیشتر از ۲۵۵ حرف باشد",
    company_name_unique: "این نام شرکت قبلاً ثبت شده است",

    markaziat_required: "مرکزیت ضروری است",
    markaziat_string: "مرکزیت باید یک رشته باشد",
    markaziat_max: "مرکزیت نباید بیشتر از ۲۵۵ حرف باشد",

    license_number_string: "شماره جواز باید یک رشته باشد",
    license_number_max: "شماره جواز نباید بیشتر از ۲۵۵ حرف باشد",
    license_number_unique: "این شماره جواز قبلاً ثبت شده است",

    license_start_date_date: "تاریخ شروع جواز باید یک تاریخ معتبر باشد",
    license_end_date_date: "تاریخ ختم جواز باید یک تاریخ معتبر باشد",
    license_end_date_after: "تاریخ ختم باید بعد از تاریخ شروع باشد",
    serialNO: "نمبر مسلسل",

    tin_string: "TIN باید یک رشته باشد",
    tin_max: "TIN نباید بیشتر از ۲۵۵ حرف باشد",
    tin_unique: "این TIN قبلاً ثبت شده است",

    descriptions_string: "توضیحات باید یک رشته باشد",
    is_approved_boolean: "وضعیت تایید باید صحیح باشد (true/false)",

    // validation messages for compnaies vehicles
    plate_no_required: "شماره پلیت ضروری است",
    plate_no_string: "شماره پلیت باید رشته باشد",
    plate_no_max: "شماره پلیت نباید بیشتر از ۱۵ حرف باشد",
    plate_no_unique: "این ترکیب شماره پلیت، درجه و ولایت قبلاً ثبت شده است",

    plate_grade_id_required: "درجه پلیت ضروری است",
    plate_grade_id_exists: "درجه پلیت در سیستم موجود نیست",

    plate_province_id_required: "ولایت پلیت ضروری است",
    plate_province_id_exists: "ولایت پلیت در سیستم موجود نیست",

    engine_no_required: "شماره انجن ضروری است",
    engine_no_string: "شماره انجن باید رشته باشد",
    engine_no_max: "شماره انجن نباید بیشتر از ۶۰ حرف باشد",
    engine_no_unique: "این شماره انجن قبلاً ثبت شده است",

    shaci_no_required: "شماره شاسی ضروری است",
    shaci_no_string: "شماره شاسی باید رشته باشد",
    shaci_no_max: "شماره شاسی نباید بیشتر از ۶۰ حرف باشد",
    shaci_no_unique: "این شماره شاسی قبلاً ثبت شده است",

    vehicle_type_id_required: "نوعیت واسطه ضروری است",
    vehicle_type_id_exists: "نوعیت واسطه در سیستم موجود نیست",

    modal_string: "مدل باید رشته باشد",
    modal_max: "مدل نباید بیشتر از ۲۵۵ حرف باشد",

    vehicle_color_string: "رنگ واسطه باید رشته باشد",
    vehicle_color_max: "رنگ واسطه نباید بیشتر از ۴۰ حرف باشد",

    is_approved_boolean: "وضعیت تایید باید true یا false باشد",

    image_image: "فایل انتخاب‌شده باید یک تصویر باشد",
    image_mimes: "نوع فایل تصویر باید jpg، jpeg، png، gif یا webp باشد",
    image_max: "حجم تصویر نباید بیشتر از ۲ مگابایت باشد",

    file_file: "فایل باید معتبر باشد",
    file_mimes: "فایل باید یکی از نوع‌های: pdf، doc، docx، xls، xlsx باشد",
    file_max: "حجم فایل نباید بیشتر از ۲ مگابایت باشد",

    // outgoing vehicles validation messages
    Terminal_not_found: "ترمینل پیدا نشد",
    Branch_not_found: "نماینده‌گی پیدا نشد",
    Company_not_found_in_terminal: "شرکت در ترمینل پیدا نشد",

    totalStoredVehicles: "مجموع وسایط ثبت‌ شده",
    totalApprovedVehicles: "مجموع وسایط تأیید شده",
    totalLargeVehicles: "مجموع وسایط بزرگ",
    totalSmallVehicles: "مجموع وسایط کوچک",
    totalApprovedLargeVehicles: " وسایط بزرگ تأیید شده",
    totalApprovedSmallVehicles: "وسایط کوچک تأیید شده",
    approvedDrivers: "راننده ګان تایید شده",
    approvedOwners: "مالکین تایید شده",

    prof: {
        title: "معلومات پروفایل",
        description: "معلومات پروفایل و ایمیل خود را تازه بسازید.",
        name: "نام",
        email: "ایمیل",
        unverified: "آدرس ایمیل شما تأیید نشده است.",
        resendVerification: "برای ارسال دوباره ایمیل تأیید اینجا کلیک کنید.",
        verificationSent: "لینک تأیید تازه به ایمیل شما ارسال شد.",
        save: "ذخیره",
        saved: "ذخیره شد.",
    },
    pass: {
        title: "تغییر پسورد عبور",
        description:
            "اطمینان حاصل کنید که حساب شما از یک پسورد عبور طولانی و تصادفی استفاده می‌کند.",
        current: "پسورد عبور فعلی",
        new: "پسورد عبور جدید",
        confirm: "تکرار پسورد عبور",
        save: "ذخیره",
        saved: "ذخیره شد.",
    },

    loads: "اعلان بار",
    queues: "تنظیم نوبت",
    newqueue: "نوبت جدید",
    addNewQueue: "اضافه کردن نوبت جدید",
    destinationProvince: "ولایت مقصد",
    selectQueueType: "نوعیت قطار نوبت را انتخاب کنید",
    queueDashboard: "تنظیم نوبت",
    fareMustBetween:"کرایه باید بین {{min}} و {{max}} باشد",
};

export default dari;
