// src/locales/dari.js
const dari = {
    amis: "سیستم مدیریت میدان‌های هوایی",

    dari: "دری",
    pashto: "پښتو",

    login: {
        email: "ایمیل",
        enterEmail: "ایمیل خود را وارد کنید",
        password: "رمز عبور",
        enterPassword: "رمز عبور خود را وارد کنید",
        rememberMe: "مرا به خاطر بسپار",
        forgotPassword: "رمز عبور خود را فراموش کرده‌اید؟",
        enter: "ورود به سیستم",
    },

    emailIsNeeded: "ایمیل ضروری است",
    emailIsInvalid: "ایمیل معتبر نیست",
    passwordIsNeeded: "رمز عبور ضروری است",
    credentialInvalid: "ایمیل یا رمز عبور نادرست است",

    common: {
        dashboard: "داشبورد",
        loading: "لطفاً صبر کنید...",
        name: "نام",
        namePashto: "نام (پشتو)",
        nameDari: "نام (دری)",
        nameEnglish: "نام (انگلیسی)",
        province: "ولایت",
        district: "ولسوالی",
        selectProvince: "ولایت را انتخاب کنید",
        selectDistrict: "ولسوالی را انتخاب کنید",
        activityStatus: "وضعیت فعالیت",
        approvalStatus: "وضعیت تأیید",
        action: "عملیات",
        approve: "تأیید",
        disApprove: "رد",
        NO: "شماره",
        date: "تاریخ",
        time: "زمان",
        edit: "ویرایش",
        editInfo: "ویرایش معلومات",
        updating: "در حال بروزرسانی...",
        saveChanges: "ذخیره تغییرات",
        add: "افزودن",
        storInfo: "ذخیره معلومات",
        storingInfo: "در حال ذخیره معلومات...",
        next: "بعدی",
        previous: "قبلی",
        descriptions: "توضیحات",
        search: "جستجو",
        searching: "در حال جستجو...",
        delete: "حذف",
        clear: "پاک کردن",
        goBack: "بازگشت",
        type: "نوع",
    },

    measurement: {
        area: "مساحت",
        meter: "متر",
        kilometer: "کیلومتر",
        squareMeter: "متر مربع",
        hectare: "هکتار",
        kilogram: "کیلوگرام",
        gram: "گرام",
        liter: "لیتر",
        ton: "تن",
        foot: "فوت",
        mile: "مایل",
    },

    airport: {
        airport: "میدان هوایی",
        airports: "میدان‌های هوایی",
        addNewAirport: "افزودن میدان هوایی جدید",
        airportInfo: "معلومات میدان هوایی",
        airportCode: "کود میدان هوایی",
        runwayLength: "طول باند",
        runwayWidth: "عرض باند",
        airportType: "نوع میدان هوایی",
    },

    flight: {
        flight: "پرواز",
        flights: "پروازها",
        flightNumber: "شماره پرواز",
        airline: "شرکت هوایی",
        departure: "حرکت",
        arrival: "رسیدن",
        departureTime: "زمان حرکت",
        arrivalTime: "زمان رسیدن",
        origin: "مبدأ",
        destination: "مقصد",
    },

    passenger: {
        passenger: "مسافر",
        passengers: "مسافران",
        passportNumber: "شماره پاسپورت",
        nationality: "تابعیت",
        gender: "جنسیت",
        male: "مرد",
        female: "زن",
    },

    airline: {
        airline: "شرکت هوایی",
        airlines: "شرکت‌های هوایی",
        airlineName: "نام شرکت هوایی",
        country: "کشور",
    },

    report: {
        reports: "گزارش‌ها",
        dailyReport: "گزارش روزانه",
        monthlyReport: "گزارش ماهانه",
        yearlyReport: "گزارش سالانه",
        generateReport: "تولید گزارش",
    },

    user: {
        users: "کاربران",
        addUser: "افزودن کاربر جدید",
        username: "نام کاربری",
        email: "ایمیل",
        password: "رمز عبور",
        role: "نقش",
        permissions: "اجازه‌ها",
    },
};

export default dari;
