// src/locales/pashto.js
const pashto = {
    welcomeMessage:
        "د حیرتان بندر باروړونکو وسایطو ترمینل دمدیریت سیستم ته ښه راغلاست",
    dashboard: "اصلی صفحه",
    setting: "ثبت برخه",
    outDoor: "خروجی دروازه",
    inDoor: "دخولی دروازه",
    reports: "راپورونه",
    users: " کاروونکي",
    profile: "اکونټ",
    userType: " د کاروونکي ډول",
    usersList: "د کاروونکو لیست",
    vehiclesTypes: "د موټرو ډولونه",
    vehiclesOwners: "د موټرو مالکین",
    editOwner: "د مالک اصلاح کول",
    drivers: "موټر چلوونکي",
    companies: "ټرانسپورټي شرکتونه",
    terminals: "ترمینلونه",
    terminal: "ترمینل",
    routes: "لارې",
    route: "لاره",
    relatedRoutes: "اړوند لارې",
    routeNotFound: "کومه لاره نشته",
    transportation_fee: "ترانسپورتی حق الخدمت",
    fare: "کرایه",
    editFare: "د کرایه تغیر کول",
    bandars: "کنټرولي بندرونه",
    status: "حالت",
    action: "عملیات",
    save: "ثبتول",
    saving: "د ثبتولو په حال کی ...",
    NO: "شمیره",
    disable: "غیر فعالول",
    approved: "منل شوی",
    approve: "منل ",
    notApproved: "ندی منل شوی",
    editInfo: "سمول",
    reNew: "تمدید کول",
    update: "د بدلونونه ثبتول",
    updating: "د بدلونونه د ثبتولو په حال کې ...",
    goBack: "شاته تګ",
    searchByName: "د نوم له مخې یې ولټوئ",
    search: "لټون",
    searching: "لټون ...",
    search_driver: "د موټر چلوونکي لټون",
    search_by_name_or_id: "د بشپړ نوم یا ملی تذکرې له مخې ولټوئ",
    allProvinces: "ټول ولایتونه",
    percentage: "فیصدي",
    additionalFee: "اضافي پیسې",

    profile: "اکونټ",
    editProfile: "د اکونټ سمون",
    pashto: "پښتو",
    persion: "فارسی",
    login: "سیستم ته دننه کیدل",
    loginToYourAcount: "خپل حساب ته دننه شئ",
    welcomBack:
        "د حیرتان بندر باروړنکو وسایطو ترمینل دمدیریت سیستم ته ښه راغلاست",
    forgotPassword: "پاسورډ/رمز هیر شوی؟",
    rememberMe: "ما یاد ساتئ",
    logout: "له سیستم څخه وتل",
    loggingOut: "له سیستم څخه وتل ...",
    storedSuccessfully: "معلومات په بریالیتوب سره ثبت شول ",
    updatedSuccessfully: "معلومات په بریالیتوب سره بدل شول ",
    renewedSuccessfully: "معلومات په بریالیتوب سره تمدید شول",
    upprovedSuccessfully: "معلومات په بریالیتوب سره ومنل شول",
    disabledSuccessfully: "معلومات په بریالیتوب سره رد شول",
    approveInfo: "د معلوماتو منل",
    areYouSure: "آیا تاسو ډاډه یاست ؟",
    yesChange: "هو، بدل شي",
    cancel: "پریښوودل",
    close: "بندول",
    changeStatus: "د حالت بدلول",
    unApprovedStatus: "حالت مسترد شولو",
    areYouSureToChangeStatus: "آیا تاسو ډاډه یاست ترڅو حالت بدل کړئ",
    vehilcesTypesList: "د موټرو د ډولونو لیست ",
    vehicleType: "د موټر ډول",
    vehicleCapacity: "د موټر ظرفیت",
    newType: "نوی نوعیت",
    addVehicleType: "د موټر د ډول اضافه کول",
    editVehicleType: "د موټر د ډول سمول",
    vehicleOwnersList: "د موټرو د مالکینو لیست",
    name: "نوم",
    fatherName: "د پلار نوم",
    nationalID: "د تذکیرې شمیره",
    phoneNO: "د تلیفون شمیره",
    image: "انځور",
    vehicleOwnerImage: "د موټرو دمالک انځور",
    documents: "اسناد",
    newOwner: "نوی مالک",
    addVehicleOwner: "د موټر د مالک اضافه کول",
    addvehicleDriver: "د موټر چلوونکی اضافه کول",
    selectImage: "د انځور ټاکل",
    selectDocument: "د اسنادو ټاکل",
    changeVehicleOwnerInfo: "د موټر د مالک د معلوماتو سمول ",
    driversList: "د موټرچلوونکيو لیست",
    newDriver: "نوی موټرچلوونکی",
    editDriver: "د موټرچلوونکي سمول",
    addNewDriver: "د نوي موټرچلوونکي اضافه کول",
    changeDriverInfo: "د موټرچلوونکي د معلوماتو سمول",
    driverImage: "د موټرچلوونکي انځور",
    is_driver_owner_too: "آیا موټرچلوونکی هم مالک دی؟",
    is_owner_driver_too: "آیا مالک هم موټرچلوونکی دی؟",
    yes_also_owner: "هو، موټرچلوونکی هم مالک دی",
    yes_also_driver: "هو، مالک هم موټرچلوونکی دی",
    companiesList: "د شرکتونو لیست",
    expiredLisenses: "له وخت څخه تیر شوي جوازونه",
    companyName: "د شرکت نوم",
    markaziat: "مرکزیت",
    TIN: "TIN شمیره",
    lisenseStartDate: "د جواز د پیل نیټه",
    lisenseEndDate: "د جواز د پای نیټه",
    lisenceNumber: "د جواز شمیره",
    newCompany: "نوی شرکت",
    addNewCompany: "د نوي شرکت اضافه کول",

    SearchYourDesiredVehicle: "خپل مطلوب موټر دلته ولټوئ",
    plateShaciEngineNO: "پلیټ، شاسي یا انجن شمیره مو دلته دننه کړئ",

    changeCompanyInfo: "د شرکت د معلوماتو بدلول",
    vehicles: "موټرونه",
    branches: "نماینده ګۍ",
    companyBranches: "د شرکت نماینده ګۍ",
    addBranch: "د نماینده ګۍ اضافه کول",
    addBranchToCompany: "د شرکت نماینده ګۍ اضافه کول",
    activityTypes: "د فعالیت ډولونه",
    companyLisenceExpired: "د شرکت د جواز نیټه پای ته رسیدلې ده",
    companyVehiclesList: "  د {{name}} شرکت د لویو موټرو لیست",
    companySmallVehiclesList: "  د {{name}} شرکت د کوچنیو موټرو لیست",
    viewHistory: "تاریخچه وګورئ",
    plateNO: "پلیټ شمیره",
    engineNO: "انجن شمیره",
    shaciNO: "شاسي شمیره",
    vehicleModal: "د موټر ماډل",
    vehicleColor: "د موټر رنګ",
    vehicleOwner: "د موټر مالک",
    newVehicle: "نوې موټر",
    addNewVehilce: "د نوې موټر اضافه کول",
    plateGrade: "د پلیټ درجه",
    selectGrade: "درجه وټاکئ",
    plateProvince: "د پلیټ ولایت",
    selectProvince: "ولایت وټاکئ",
    selectTerminal: "ترمینل وټاکئ",
    selectDistrict: "ولسوالي وټاکئ",
    vehicleDriver: "د موټر موټرچلوونکی",
    vehicleImage: "د موټر انځور",
    changeVehicleInfo: "د موټر د معلوماتو بدلول",
    changeVehicleCompany: "د موټر د شرکت بدلول",
    deActive: "غیر فعالول",
    noResultFound: "کومه پایله ونموندل شوه",
    companyBranchesList: "د {{name}} شرکت د نماینده گیو لیست",
    province: "ولایت",
    descriptions: "توضیحات",
    newBranch: "نوې نماینده ګي",
    addNewBranch: "د نوې نماینده ګۍ اضافه کول",
    changeBranch: "د نماینده ګۍ بدلول",
    companyActivityTypeList: "د شرکت د فعالیت ډولونه",
    newActivity: "نوی فعالیت",
    addNewActivityType: "د نوي فعالیت اضافه کول",
    changeActivityType: "د فعالیت د ډول بدلول",
    activityType: "د فعالیت ډول",
    terminalsList: "د ترمینلونو لیست",
    terminalName: "د ترمینل نوم",
    location: "پته",
    newTerminal: "نوی ترمینل",
    addNewTerminal: "د نوي ترمینل اضافه کول",
    changeTerminalInfo: "د ترمینل د معلوماتو بدلول",
    routesList: "د لارو لیست",
    newRoute: "نوې لاره",
    addNewRoute: "د نوې لارې اضافه کول",
    startingProvince: "د پیل ولایت",
    endingProvince: "د پای ولایت",
    startingDistrict: "د پیل ولسوالي",
    endingDistrict: "د پای ولسوالي",
    changeRouteInfo: "د لارې د معلوماتو بدلول",
    fareList: "د کرایې لیست",
    startDate: "د پیل نیټه",
    newFare: "نوې کرایه",
    editFare: "د کرایې  سمول",
    addNewFare: "د نوې کرایې اضافه کول",
    changeFareInfo: "د کرایې د معلوماتو بدلول",
    selectRoute: "لاره غوره کړئ",
    selectVehicleType: "د موټر نوعیت غوره کړئ",
    bandarsList: "د کنټرولي بندرونو لیست",
    bandarName: "د بندر نوم",
    newBandar: "نوی بندر",
    editBandar: "د بندر تغیرول",
    addNewBandar: "د نوي بندر اضافه کول",
    changeBandarInfo: "د بندر د معلوماتو بدلول",
    smallVehicles: "کوچني موټرونه",
    addSmallVehicle: "کوچني موټر اضافه کول",
    editSmallVehicle: "کوچني موټر سمول",
    smallVehiclesList: "د کوچنیو موټرو لیست",
    vehicleRoutes: "د موټر لارې",
    addCompany: "د شرکت اضافه کول",
    largeVehicles: "لوی موټرونه",
    Vehicles: "لوی موټرونه",
    todayOutgoingVehicles: "نن ورځ وتلي موټرونه",
    outgoingVehiclesList: "د تلونکو وسایطو لیست",
    company: "شرکت",
    vehicleCatagory: "د موټر کتګوري",
    addVehicleToCompany: "{{company}} ته موټر اضافه کړئ",

    outDate: "د وتلو نیټه",
    outTime: "د وتلو وخت",
    newOutgoingVehilce: "نوې تلونکې موټر",
    addNewOutgoingVehicle: "د نوې تلونکې موټر اضافه کول 🚙",
    enterOutgoingVehicleShaciNO: "د تلونکې موټر شاسي شمیره دننه کړئ",
    chalanNO: "چالان شمیره",
    helper: "مرسته کوونکی",
    rented: "دربست شوی",
    outgoingVehilceType: "د تلونکې موټر ډول",
    normal: "عادی",
    damagedVehiclePlateNO: "د خراب شوې موټر پلیټ شمیره",
    details: "تفصیلات",
    viewDetails: "د تفصیلاتو نه لیدنه",
    totalCars: "ټول موټر",
    totalVehicles: "ټول موټر",
    routeFareNotDefined: "ددې لارې کرایه تراوسه نده مشخصه شوې",
    printToken: "ټوکن پرینټ کول",
    veiwDetails: " تفصیلات لیدل",
    outedVehicleDetails: "د تللې موټر تفصیلات",
    from: "له ",
    to: "تر",
    routeFare: "د لارې کرایه",
    vehicleStatus: "د موټر حالت",
    last30DaysIncome: "د تیرو ۳۰ ورځو عاید",

    passengersInfo: "د مسافرو معلومات",
    passengersNO: "د مسافرو شمیر",
    movementDate: "د حرکت نیټه",
    movementTime: "د حرکت وخت",
    vehicleInfo: "د موټر معلومات",
    waiting: "د انتظار په حال کې...",
    reject: "ردول",
    rejected: "رد شوی",
    rejectReason: "د ردولو دلیل",
    makeDamage: "خرابول",
    damageReason: "د خرابیدلو دلیل",
    damaged: "خراب شوی",
    print: "پرینټ کول",
    terminalInfo: "د ترمینل تفصیلات",
    damageIsPossibleIn24H: "خرابیدل یوازې په ۲۴ ساعتونو کې امکان لري",
    undefined: "نا معلوم",
    imageNotAvailable: "کوم انځور نشته",
    branchNotAvailable: "نماینده ګي شتون نه لري",
    outedVehicles‌basedOnTerminal: "تللي موټر د ترمینل پر بنسټ",
    outedvehileReportBasedOnPalate: "تللي موټر د پلیټ شمیرې پر بنسټ",
    largeOutedVehiclesReportsBasdOnCompany: "تللي موټر د شرکت پر بنسټ",
    endDate: "د پای نیټه",
    reportType: "د راپور ډول",
    totalReport: "اجمالي راپور",
    descriptiveReport: "تفصیلي راپور",
    generateReport: "راپور اخیستل",
    generatingReport: "راپور اخیستل...",
    terminalLocation: "د ترمینل پته",
    branch: "نماینده ګي",
    farePerPerson: "کرابه في نفر",
    totalFare: "ټول ترانسپورتي حق الخدمت",
    total: "ټول",
    transportationFee: "ټرانسپورټي حق الخدمت",
    totalTransportationFee: "ټول ټرانسپورټي حق الخدمت",
    selectCompany: "کمپنۍ غوره کړئ",
    vehiclesNO: "د موټرو شمیر",
    bandarStatus: "د بندر حالت",
    checkTime: "چیک وخت",
    checkBandar: "چیک کوونکی بندر",
    checker: "چیک کوونکی",

    roles: "صلاحیتونه",
    newUser: "نوی کارکوونکی",
    email: "بریښنالیک",
    role: "صلاحیت",
    type: "ډول",
    addNewUser: "د نوي کارکوونکي اضافه کول",
    changeUserInfo: "د کاروونکي د معلوماتو بدلول",
    password: "پاسورډ/رمز",
    confirmPassword: "پاسورډ/رمز تایید کړئ",

    newRole: "نوی صلاحیت/ رول",
    editRole: "د صلاحیت/ رول سمول",
    addNewRole: "د نوي صلاحیت/ رول اضافه کول",
    roleName: "د صلاحیت/ رول نوم",
    changeRoleInfo: "د صلاحیت/ رول د معلوماتو بدلول",
    rolesList: "د صلاحیتونو لیست",
    permissions: "اجازې",
    enterEmailHere: "بریښنالیک دلته دننه کړئ",
    enterPasswordHere: "پاسورډ/ رمز دلته دننه کړئ",
    systemColor: "د سیستم رنګ",
    systemLanguage: "د سیستم ژبه",
    openUserMenu: "د کاروونکي مینو پرانیزئ",

    summary: "لنډیز",
    monthlyRevenue: "میاشتني عواید",
    largeVehiclesRevenueGraph: "د لویو موټرو د عواید ګراف",
    transportationCompanies: "ټرانسپورټي شرکتونه",
    figuresBasedCharts: "د چارټونو پر بنسټ ارقام",
    revenueStatisticsSystem: "د مسافروړونکو موټرو د عوایدو او احصایې سیستم",
    actionInSystem: "په سیستم کې کړنې",
    grade: "رتبه",
    scores: "نمرې",
    figures: "ارقام",

    vehicleTypeIsNeeded: "د موټر نوعیت ټاکل اړین دي!",
    vehicleCapacityIsNeeded: "د موټر ظرفیت ټاکل اړین دي!",
    nameIsNeeded: "نوم اضافه کول اړین دي!",
    fatherNameIsNeeded: "د پلار نوم اضافه کول اړین دي!",
    phoneNOIsNeeded: "تلیفون شمیره اضافه کول اړین دي!",
    nationIDIsNeeded: "تذکرې شمیره اړین دي!",
    documentIsNeeded: "اسناد اضافه کول اړین دي!",
    imageIsNeeded: "انځور اضافه کول اړین دي!",
    phoneNOShouldBeValid: "د اړیکې شمیره باید یوه معتبره شمیره وي ",
    maxFileSize300: "د اسنادو حجم باید له ۳۰۰ څخه زیات نه وي",
    documentIsNeeded: "اسناد اړین دي",
    unvaliedFileType: "ناسم فایل ډول",
    pdfIsAllowed: "اسناد باید په pdf شکل کې اضافه شي",
    companyNameIsNeeded: "د کمپنۍ نوم اړین دی",
    markaziatIsNeeded: "مرکزیت اړین دی",
    date: "نیټه",
    lisenseNumberIsNeeded: "د جواز شمیره اړینه ده",
    TINIsNeeded: "TIN شمیره اړینه ده",
    startDateIsNeeded: "د پیل نیټه اړینه ده",
    endDateIsNeeded: "د پای نیټه اړینه ده",
    plateNOIsNeeded: "پلیټ شمیره اړینه ده",
    plageGradeIsNeeded: "پلیټ درجه اړینه ده",
    provinceIsNeeded: "ولایت ټاکل اړین دي",
    engineNOIsNeeded: "انجن شمیره اړینه ده",
    shaciNOIsNeeded: "شاسي شمیره اړینه ده",
    vehicleModalIsNeeded: "د موټر ماډل اړین دی",
    vehicleColorIsNeeded: "د موټر رنګ اړین دی",
    terminalNameIsNeeded: "د ترمینل نوم اړین دی",
    terminalIsNeeded: " ترمینل اړین دی",
    locationIsNeeded: "موقعیت ټاکل اړین دی",
    companyIsNeeded: "شرکت ټاکل اړین دی",
    routIsNeeded: "مسیر ټاکل اړین دی",
    atleastSelectOneRoute: "حد اقل باید یوه لاره وټاکئ",
    startingProvinceIsNeeded: "د پیل ولایت اړین دی",
    endingProvinceIsNeeded: "د پای ولایت اړین دی",
    startingDistrictIsNeeded: "د پیل ولسوالي اړینه ده",
    endingDistrictIsNeeded: "د پای ولسوالي اړینه ده",
    fareIsNeeded: "کرایه اړینه ده",
    bandarIsNeeded: "د بندر نوم اړین دی ",
    routeIsNeeded: "لاره ټاکل اړین دي",
    chalanIsNeeded: "چالان شمیره اړینه ده",
    rejectReasonIsNeeded: "د رد دلیل اړین دی",
    damageReasonIsNeeded: "د خرابوالي دلیل اړین دی",
    reportTypeIsNeeded: "د راپور ډول اړین دی",
    emailIsInvalid: "بریښنالیک ناسم دی",
    credentialInvalid: "برېښنالیک یا پټنوم غلط دی.",
    emailIsNeeded: "بریښنالیک اړین دی",
    passwordIsNeeded: "پاسورډ/رمز اړین دی",
    minPasswordShouldBe4NO: "پاسورډ/رمز باید کم تر کم ۴ عدده وي",
    passwordShouldBeSame: "پاسورډ/رمز باید ورته وي ",
    confirmPasswordIsNeeded: "د پاسورډ/رمز تایید اړین دی",
    typeIsNeeded: "ډول اړین دی",
    roleIsNeeded: "صلاحیت ټاکل اړین دی",

    copyright:
        "د کاپی ټول حقوق خوندي دي. د مسافروړونکو موټرو د عوایدو او احصایې سیستم",
    motaIea: "د افغانستان اسلامي امارت. د ټرانسپورټ او هوایي چلند وزارت",

    next: "وروستنی",
    previous: "مخکینی",
    log: "لاګ",

    filterOptions: "د لټون لپاره د فلټر کولو آپشنونه",
    selectDistrict: "ولسوالی وټاکئ",
    selectProvince: "ولایت وټاکئ",
    selectCompany: "شرکت وټاکئ",
    selectType: "ډول وټاکئ",
    selectVehicle: "موټر وټاکئ",
    selectDriver: "موټر چلوونکی وټاکئ",
    selectOwner: "مالک وټاکئ",
    selectBandar: "بندر وټاکئ",
    selectBranch: "شعبه وټاکئ",
    selectActivity: "فعالیت وټاکئ",
    selectFare: "کرایه وټاکئ",
    selectTerminal: "ترمینل وټاکئ",
    selectRoute: "لاره وټاکئ",
    selectVehicleType: "موټر ډول وټاکئ",
    selectVehicleOwner: "موټر مالک وټاکئ",
    selectVehicleDriver: "موټر چلوونکی وټاکئ",
    getReport: "راپور اخیستل",
    loading: "لټون ...",
    serialNO: "پرلپسې شمیره",
    vehicleListTitle: "د موټرونو لیست",
    company: "شرکت",
    platePlaceholder: "پلیټ نمبر ولیکئ",
    vehicleType: "د موټر ډول",
    vehileCompany: "د موټر شرکت",
    addNewVehicleType: "د موټر نوي ډول اضافه کړئ",
    chooseCompany: "شرکت انتخاب کړئ",
    chooseType: "د موټر ډول انتخاب کړئ",
    largeVehicle: "لوی وسایط",
    smallVehicle: "کوچنی وسایط",
    passwordNote:
        "نوټ: پاسورډ باید لږ تر لږه ۸ توري ولري او په کې حروف، شمېرې او ځانګړي نښې (لکه @، #، $) شامل وي.",
    hasDocument: "آیا موټر اسناد لري؟",
    yes: "هو",
    no: "نه",
    storeDate: "ثبتولو نیټه",
    lastUpdateDate: " وروستنی بدلون",
    wantToAddViolation: "آیا غواړئ سرغړونه اضافه کړئ؟",
    vehicleDriver: "د موټر چلوونکی",
    vehicleOwner: "د موټر مالک",
    vehicleCompany: "د موټر شرکت",
    changeVehicleCompany: "د موټر شرکت بدلول",
    licenseScanFile: "د جواز سکین فایل",
    companiesVehicles: "د شرکتونو موټرونه",

    violations: "سرغړونې",
    ownerProvince: "د مالک ولایت",
    ownerDistrict: "د مالک ولسوالۍ",
    ownerVillage: "د مالک کلی",
    addingNewVehicle: "نوی موټر اضافه کړئ",
    ListOfViolatedVehicles: "د سرغړوونکو موټرو لیست",
    vehicleOwnerDetails: "د واسطې د مالک معلومات",
    vehicleOwnerName: "د واسطې د مالک نوم",
    vehicleOwnerFName: "د مالک د پلار نوم",
    ownerVillage: "د مالک کلي",
    errorOccured: "خطا پېښه شوه، مهرباني وکړئ بیا هڅه وکړئ",
    infoNotFound: "معلومات ونه موندل شول",
    changeVehilceInfo: "د واسطې معلومات بدل کړئ",
    arrestDate: "د نیولو نېټه",
    freeDate: "د خوشې کېدو نېټه",
    violationType: "د سرغړونې ډول",
    arrestPlace: "د نیولو ځای",
    newViolation: "نوې سرغړونه",
    listOfVehicleViolations: "د واسطې د سرغړونو لیست",
    addingNewViolation: "نوې سرغړونه اضافه کړئ",
    changingViolationInfo: "د سرغړونې معلومات بدل کړئ",
    no_approved_vehicle_in_this_terminal:
        "په دې ترمینل کې کوم موټر نه دی منل شوی",
    paymentStatusPaid: "دغه تعرفه په بریالیتوب سره تادیه شوې ده.",
    tarrifPaymentStatus: "د تعرفې د تادیې وضعیت",
    checked: "کتل شوې",
    notChecked: "نده کتل شوې",
    search: "لټون",
    searchByPlateNo: "د پلیټ شمیرې له مخې ولټوئ",
    paymentStatusFailed: "د دې تعرفې لپاره هیڅ تادیه ونه موندل شوه.",
    paymentStatusNotPaid: "د تادیې وضعیت تاید شوی نه دی.",
    errorCheckingPaymentStatus: "د تادیې وضعیت د کتلو پر مهال تېروتنه وشوه.",
    helpDesk: {
        title: "مرسته ",
        titlePlaceholder: "سرلیک ولیکئ",
        descriptionPlaceholder: "خپل ستونزه تشریح کړئ",
        createTicket: "نوی پوښتنه وکړئ",
        tickets: "پوښتنې",
        by: "څخه",
        replies: "ځوابونه",
        noReplies: "هیڅ ځوابونه نشته",
        replyPlaceholder: "خپل ځواب ولیکئ",
        reply: "ځواب ورکړئ",
    },
    vehicleDetails: {
        vehicleDetails: "د موټر تفصیلات",
        title: "د موټرو تفصيلات",
        companyName: "د شرکت نوم",
        licenseNumber: "جواز شمېره",
        licenseStart: "د جواز د پيل نېټه",
        licenseEnd: "د جواز د پای نېټه",
        description: "تفصيلات",
        vehicleType: "د موټر ډول",
        plateNo: "پلېټ شمېره",
        engineNo: "انجن شمېره",
        vehicleColor: "د موټر رنګ",
        chassisNo: "شاسی شمېره",
        farePerPerson: "د هر مسافر کرايه",
        route: "لاره",
        checkBandar: "چیک کوونکی بندر",
        bandarStatus: "د بندر حالت",
        outDate: "د وتلو نېټه",
        outTime: "د وتلو وخت",
        passengers: "مسافرین",
        ownerName: "د مالک نوم",
        ownerPhone: "د مالک شمېره",
        driverName: "د چلوونکي نوم",
        driverPhone: "د چلوونکي شمېره",
        terminalName: "د ترمینل نوم",
        terminalLocation: "ځای",
        timeRemaining: "د تایید لپاره پاتې وخت",
        hours: "ساعتونه",
        timeExpired: "د تایید وخت پای ته رسېدلی دی.",
        submitReason: "دلیل ولیږئ",
        reasonPlaceholder: "د ردېدو دلیل",
        reject: "رد کول",
        damage: "خراب کول",
        approve: "منل",
    },

    common: {
        loading: "شېبه انتظار وکړئ...",
    },

    processSucceed: "چاره بریالۍ وه",
    allTypes: "ټول ډولونه",
    tarrifs: "تعرفې",
    accounts: "حسابونه",
    companyDetails: "د شرکت توضیحات",
    wantToApprove: "تاسو غواړئ دا قبول کړئ؟",
    pay: "تادیه کول",
    checkPayment: "د تادیې چیک کول",
    show: "ښوودل",
    rejectTarrif: "د تعرفې رودل",
    tarrifDescriptions: "د تعرفې توضیحات",
    bankReceipt: "د بانک رسید (آویز)",
    tarrifArrivalDate: "د تعرفې د رارسیدو نیټه",
    totalOutVehilces: "ټول بهرشوي موټرونه",
    tarrifFile: "د تعرفې فایل",
    tarrifPayment: "د تعرفې تادیه",
    tarrifsList: "د تعرفو لیست",
    addNewTarrif: "نوی تعرفه اضافه کړئ",
    tarrifNotPayed: "تعرفه نده تادیه شوې",
    problemInRetreivingData: "د معلوماتو په ترلاسه کولو کې ستونزه وه.",
    rejectedSuccessfully: "په بریالیتوب سره رد شو",
    yesAccept: "هو، قبول شي",
    newTarrif: "نوې تعرفه",
    addingNewTarrif: "د نوې تعرفې اضافه کول",
    tarrifStartDate: "د تعرفې د شروع نیټه",
    tarrifEndDate: "د تعرفې د پای نیټه",
    tarrifNO: "د تعرفې شمیره",
    checkTarrifs: "د تعرفو کتل",
    tarrifTypes: "د تعرفې ډولونه",
    tarrifsNumber: "د تعرفو شمیر",
    totalAccounts: "ټوټل حسابونه",
    savedTarrifs: "ثبت شوې تعرفې",
    payedTarrifs: "تادیه شوي تعرفې",
    pendingTarrifs: "پاتې تعرفې (انتظارشوې)",
    rejectedTarrifs: "رد شوې تعرفې",
    tarrifIsRequired: "تعرفه شمیره اړینه ده",
    tarrifNotFound: "تعرفه شمېره ونه موندل شوه",

    pending: "د انتظار په حال کی",
    saved: "ثبت شوې",
    rejected: "رد شوې",
    paid: "تادیه شوې",

    // validation messages for company
    company_name_required: "د شرکت نوم اړین دی",
    company_name_string: "د شرکت نوم باید یو سټرینګ وي",
    company_name_max: "د شرکت نوم باید تر ۲۵۵ کرکټرونو زیات نه وي",
    company_name_unique: "دا شرکت نوم مخکې ثبت شوی دی",

    markaziat_required: "مرکزیت اړین دی",
    markaziat_string: "مرکزیت باید یو سټرینګ وي",
    markaziat_max: "مرکزیت باید تر ۲۵۵ کرکټرونو زیات نه وي",

    license_number_string: "د جواز نمبر باید یو سټرینګ وي",
    license_number_max: "د جواز نمبر باید تر ۲۵۵ کرکټرونو زیات نه وي",
    license_number_unique: "دا جواز نمبر مخکې ثبت شوی دی",

    license_start_date_date: "د جواز د شروع نیټه باید یوه سمه نیټه وي",
    license_end_date_date: "د جواز د ختمیدو نیټه باید یوه سمه نیټه وي",
    license_end_date_after: "د ختمیدو نیټه باید د شروع نیټې نه وروسته وي",

    tin_string: "TIN باید یو سټرینګ وي",
    tin_max: "TIN باید تر ۲۵۵ کرکټرونو زیات نه وي",
    tin_unique: "دا TIN مخکې ثبت شوی دی",

    descriptions_string: "تشریحات باید یو سټرینګ وي",
    is_approved_boolean: "د تایید حالت باید Boolean وي (true/false)",

    // validation messages for companies vehicles
    plate_no_required: "د پلېټ نمبر اړین دی",
    plate_no_string: "د پلېټ نمبر باید سټرینګ وي",
    plate_no_max: "د پلېټ نمبر باید تر ۱۵ کرکټرونو زیات نه وي",
    plate_no_unique: "دا پلېټ نمبر، درجه او ولایت مخکې ثبت شوي دي",

    plate_grade_id_required: "د پلېټ درجه اړینه ده",
    plate_grade_id_exists: "د پلېټ درجه په سیستم کې نه ده موندل شوې",

    plate_province_id_required: "د پلېټ ولایت اړین دی",
    plate_province_id_exists: "د پلېټ ولایت په سیستم کې نه دی موندل شوی",

    engine_no_required: "د انجن نمبر اړین دی",
    engine_no_string: "د انجن نمبر باید سټرینګ وي",
    engine_no_max: "د انجن نمبر باید تر ۶۰ کرکټرونو زیات نه وي",
    engine_no_unique: "دا انجن نمبر مخکې ثبت شوی دی",

    shaci_no_required: "د شاسی نمبر اړین دی",
    shaci_no_string: "د شاسی نمبر باید سټرینګ وي",
    shaci_no_max: "د شاسی نمبر باید تر ۶۰ کرکټرونو زیات نه وي",
    shaci_no_unique: "دا شاسی نمبر مخکې ثبت شوی دی",

    vehicle_type_id_required: "د واسطې ډول اړین دی",
    vehicle_type_id_exists: "د واسطې ډول په سیستم کې نه دی موندل شوی",

    modal_string: "موډل باید یو سټرینګ وي",
    modal_max: "موډل باید تر ۲۵۵ کرکټرونو زیات نه وي",

    vehicle_color_string: "د واسطې رنګ باید سټرینګ وي",
    vehicle_color_max: "د واسطې رنګ باید تر ۴۰ کرکټرونو زیات نه وي",

    is_approved_boolean: "د تایید ارزښت باید Boolean وي (true یا false)",

    image_image: "انتخاب شوی فایل باید یو انځور وي",
    image_mimes: "د انځور ډول باید jpg، jpeg، png، gif یا webp وي",
    image_max: "د انځور اندازه باید تر ۲MB زیات نه وي",

    file_file: "فایل باید یو معتبر فایل وي",
    file_mimes: "فایل باید له دې ډولونو څخه یو وي: pdf، doc، docx، xls، xlsx",
    file_max: "د فایل اندازه باید تر ۲MB زیاته نه وي",

    // outgoing vehicles validation messages
    Terminal_not_found: "ترمینل ونه موندل شو",
    Branch_not_found: "د نماینده ګۍ ونه موندل شوه",
    Company_not_found_in_terminal: "په ترمینل کې شرکت ونه موندل شو",

    totalStoredVehicles: "ټول ثبت شوي موټرونه",
    totalApprovedVehicles: "ټول منل شوي موټرونه",
    totalLargeVehicles: " ټول لوی موټرونه",
    totalSmallVehicles: "ټول کوچني موټرونه",
    totalApprovedLargeVehicles: " منل شوي لوی موټرونه",
    totalApprovedSmallVehicles: "منل شوي کوچني موټرونه",
    approvedDrivers: "منل شوي موټر چلوونکي",
    approvedOwners: "منل شوي مالکین",
    prof: {
        title: "د پروفایل معلومات",
        description: "خپل د حساب پروفایل معلومات او برېښنالیک نوي کړئ.",
        name: "نوم",
        email: "برېښنالیک",
        unverified: "ستاسې برېښنالیک تائید شوی نه دی.",
        resendVerification: "د تائید برېښنالیک بیا لېږلو لپاره دلته کلیک وکړئ.",
        verificationSent: "یوه نوې د تائید لینک ستاسو برېښنالیک ته ولېږل شوه.",
        save: "ثبتول",
        saved: "ثبت شو.",
    },
    pass: {
        title: "رمز بدلول",
        description:
            "ډاډ ترلاسه کړئ چې ستاسو حساب د اوږده او تصادفي رمز څخه کار اخلي.",
        current: "اوسنی رمز",
        new: "نوی رمز",
        confirm: "د رمز تایید",
        save: "ثبتول",
        saved: "ثبت شو.",
    },



    loads: "بارونه",

    queues: "نوبت",
    newqueue: "نوې نوبت",
    addNewQueue: "د نوې نوبت اضافه کول",
    destinationProvince: "د بار ولایت",
    queueList: "د نوبت لیست",
    addToQueue: "نوبت ته اضافه کول",
    removeFromQueue: "له نوبت څخه حذف کول",
    selectQueueType: "د نوبت ډول انتخاب کړئ",
    queueDashboard: "د نوبت ډشبورډ",
    fareMustBetween: "کرایه باید بین {{min}} و {{max}} وی",
    
};

export default pashto;
