import {
    Construction
} from "lucide-react";

// src/locales/pashto.js
const pashto = {
    amis: "د هوایي ډګرونو د مدیریت سیستم",

    dari: "دري",
    pashto: "پښتو",

    login: {
        email: "برېښنالیک",
        enterEmail: "خپل برېښنالیک دلته دننه کړئ",
        password: "پټنوم",
        enterPassword: "خپل پټنوم دننه کړئ",
        rememberMe: "ما په یاد وساته",
        forgotPassword: "پټنوم مو هېر کړی؟",
        enter: "سیستم ته ننوتل",
    },

    common: {
                runwayDetails:"د رنوې تفصیلات",

        dashboard: "ډشبورډ",
        loading: "مهرباني وکړئ لږ صبر وکړئ...",
        name: "نوم",
        namePashto: "نوم (پښتو)",
        nameDari: "نوم (دري)",
        nameEnglish: "نوم (انګلیسي)",
        province: "ولایت",
        district: "ولسوالي",
        selectProvince: "ولایت وټاکئ",
        selectDistrict: "ولسوالي وټاکئ",
        action: "عملیات",

        NO: "شمیره",
        date: "نېټه",
        storedDate: "د ثبت نیټه",
        time: "وخت",
        edit: "سمول",
        editInfo: "معلومات سمول",
        updating: "د معلوماتو تازه کول...",
        saveChanges: "بدلونونه خوندي کول",
        save: "زخیره کول",
        saving: "د معلوماتو ذخیره کول...",
        cancel: "لغوه کول",
        close: "بندول",
        view: "کتل",
        viewInfo: "معلومات کتل",
        update: "تغیر کول",
        add: "اضافه کول",
        storInfo: "معلومات ثبت کړئ",
        storingInfo: "معلومات خوندي کېږي...",
        next: "وروستنی",
        previous: "مخکینی",
        descriptions: "تشریحات",
        description: "تشریحات",
        search: "لټون",
        searching: "لټون روان دی...",
        delete: "حذف",
        clear: "پاکول",
        goBack: "شاته تګ",
        type: "ډول",

        image: "انځور",
        log: "لاګ",
        profile: "پروفایل",
        isBlocked: "آیا بند شوی",
        informationtStoredSuccessfully: "معلومات په بریالیتوب سره ثبت شول",
        informationtUpdatedSuccessfully: "معلومات په بریالیتوب سره بدل شول",
        informationtApprovedSuccessfully: "معلومات په بریالیتوب سره ومنل شول",
        noInfoFound:"کوم معلومات و نموندل شود",


        width: "بر (سور)",
        widthUnit: "د بر(سور) و اندازه کولو واحد",
        length: "اوږدوالی",
        lengthUnit: "د اووږدوالي اندازه کولو واحد",
        latitude: "عرض البلد",
        longitude: "طول البلد",
        weaknesses: "د ضعف نقطې",
        requirements: "اړتیاوې",
        details: "تفصیلات",
        viewInfo: "معلومات وګورئ",

        addMoreProperties: "نورې ځانګړتیاوې اضافه کړئ",
        moreProperties: "نورې ځانګړتیاوې",
        propertyName: "د ځانګړتیا نوم",
        propertyValue: "د ځانګړتیا مقدار",
        remove: "لرې کړئ",
        unit: "واحد",
        reset: "پاکول",
        documents: "اسناد",
        status: "د تایدی حالت",
        cheangeStatus: "تاید کول",
        errorOccured:"یوه تېروتنه رامنځته شوه!",
        confirmDelete:"آیا Delete شي!",
        deletedSuccessfully:"په بریالیتوب سره لرې شو"


    },

    input: {
        enterName: "نوم دننه کړئ",
        enterUserEmail: "د کارونکي ایمیل دننه کړئ",
        enterUserPassword: "پټنوم دننه کړئ",
        enterPasswordConfirmation: "د پټنوم تایید دننه کړئ",
        enterPositionTitle: "د دندې سرلیک دننه کړئ",
        enterRoleName: "د صلاحیت نوم دلته دننه کړئ",

        selectRole: "صلاحیت وټاکئ",
        selectAirport: "هوایي ډګر وټاکئ",
        selectGeneralBranch: "عمومي څانګه وټاکئ",
        selectFile: "فایل وټاکئ",
        selectActivityState: "د فعالیت حالت وټاکئ",
        selectConstruction: "د خوښې ودانۍ وټاکئ",
        selectConstructionType: "د ودانۍ د جوړښت ډول وټاکئ",
        selectUnit: "د اندازه کولو واحد وټاکئ",
    },

    error: {
        general: "یو څه غلط شول! مهرباني وکړئ معلومات وګورئ، یا له ادمین سره اړیکه ونیسئ.",
        required: "دا برخه اړینه ده.",
        credentialInvalid: "برېښنالیک یا پټنوم ناسم دی",

        fieldIsNeeded: "دا برخه ډکول اړین دي.",
        selectionIsInvalid: "ټاکل شوی انتخاب سم نه دی.",
        shouldBeDecimal: " باید تر دوو اعشاري ځایونو پورې وي.",
        shouldBeNumber: " باید یوه معتبره شمېره وي.",
        latitudeOutOfRange: "عرض البلد باید د -90 او 90 ترمنځ وي.",
        longitudeOutOfRange: "طول البلد باید د -180 او 180 ترمنځ وي.",
        shouldBeString: "دا باید متن وي.",
        max255Characters: "اعظمي ۲۵۵ توري اجازه لري.",

        upperCase: "لوی انګلیسي حروف اړین دي!",
        englishString: "اړینه ده چې حروف انګلیسي واوسي!",

        nameIsNeeded: "نوم اړین دی",
        emailIsNeeded: "برېښنالیک اړین دی",
        emailIsInvalid: "برېښنالیک سم نه دی",
        emailAlreadyExists: "دا برېښنالیک مخکې ثبت شوی",

        passwordTooShort: "پټنوم ډېر لنډ دی",
        passwordNotMatch: "پټنوم سره برابر نه دی",
        passwordInvalid: "پټنوم ناسم دی",

        roleIsNeeded: "صلاحیت ټاکل اړین دی",
        roleInvalid: "صلاحیت ناسم دی",
        roleNotFound: "صلاحیت ونه موندل شو",

        nameAlreadyExists: "دا نوم مخکې ثبت شوی",
        permissionIsNeeded: "اجازې ټاکل اړین دي",
        permissionBeList: "اجازې باید یو باوري لیست وي.",

        airportIsNeeded: "هوایي ډګر ټاکل اړین دی",
        airportInvalid: "هوایي ډګر ناسم دی",
        generalDepartmentInvalid: "عمومي څانګه ناسمه دی",
        positionTitleIsNeeded: "د دندې سرلیک اړین دی",

        passwordIsNeeded: "مهرباني وکړئ پټنوم داخل کړئ.",
        passwordInvalid: "اوسنی پټنوم ناسم دی.",
        confirmPasswordInvalid: "د پټنوم تایید سم نه دی.",
        passwordMin: "پټنوم باید لږ تر لږه ۸ توري ولري.",

        passwordLetters: "پټنوم باید لږ تر لږه یو حرف ولري.",
        passwordMixedCase: "پټنوم باید لوی او کوچني حروف ولري.",
        passwordNumbers: "پټنوم باید لږ تر لږه یو عدد ولري.",
        passwordSymbols: "پټنوم باید لږ تر لږه یو ځانګړی نښه ولري.",
        trainingPlans: {
            endDateAfterStart: "د پای نېټه باید د پیل نېټې وروسته وي.",
            futureDate: "د پیل نېټه باید د اوسني وخت وروسته وي.",
        },



        airline: {
            name_en_required: "د هوايي شرکت انګلیسي نوم اړین دی.",
            name_en_unique: "دا انګلیسي نوم مخکې ثبت شوی دی.",
            name_dr_required: "د هوايي شرکت دري نوم اړین دی.",
            name_dr_unique: "دا دري نوم مخکې ثبت شوی دی.",
            name_ps_required: "د هوايي شرکت پښتو نوم اړین دی.",
            name_ps_unique: "دا پښتو نوم مخکې ثبت شوی دی.",
        },
        sgha_service: {
            name_en_required: "د خدمت انګلیسي نوم اړین دی.",
            name_en_unique: "دا انګلیسي نوم مخکې ثبت شوی دی.",
            unit_required: "د خدمت واحد ټاکل اړین دي.",
            unit_invalid: "ټاکل شوی د خدمت واحد سم نه دی.",
            airline_rates_required: "لږ تر لږه د یوې هوايي شرکت نرخ داخلول اړین دي.",
            airline_rates_invalid: "د هوايي شرکتونو د نرخونو معلومات سم نه دي.",
            airline_rates_min: "لږ تر لږه یو هوايي شرکت باید اضافه شي.",
            airline_required: "د هوايي شرکت ټاکل اړین دي.",
            airline_invalid: "ټاکل شوی هوايي شرکت سم نه دی.",
            airline_duplicate: "یو هوايي شرکت یوازې یو ځل اضافه کېدای شي.",
            rate_required: "د خدمت نرخ اړین دی.",
            rate_numeric: "د خدمت نرخ باید عددي وي.",
            rate_min: "د خدمت نرخ باید له صفر څخه کم نه وي.",
        },
        organization: {
            name_is_required: "د ادارې نوم اړین دی.",
            name_unique: "دا نوم مخکې ثبت شوی دی.",
            code_unique: "دا کوډ مخکې ثبت شوی دی.",
            email_email: "برېښنالیک باید د برېښنالیک په بڼه وي.",
            email_unique: "دا برېښنالیک مخکې ثبت شوی دی.",
            phone_unique: "دا د اړیکې شمېره مخکې ثبت شوی دی.",
            website_url: "وېب‌پاڼه باید د وېب‌پاڼې په بڼه وي.",
        },
        tashkil: {
            year_required: "کال اړین دی.",
            year_integer: "کال باید بشپړ عدد وي.",
            year_min: "کال باید لږ تر لږه 1000 وي.",
            year_max: "کال باید له 9999 څخه زیات نه وي.",
            organization_year_unique: "د دې ادارې لپاره د همدې کال تشکیل مخکې ثبت شوی دی.",
            reference_number_required: "د مرجع شمېره اړینه ده.",
            reference_number_string: "د مرجع شمېره باید متن وي.",
            reference_number_max: "د مرجع شمېره باید له 255 تورو زیاته نه وي.",
            reference_number_unique: "د مرجع شمېره مخکې ثبت شوې ده.",
            organization_id_required: "د ادارې ټاکل اړین دي.",
            organization_id_exists: "ټاکل شوې اداره معتبره نه ده.",
            description_string: "تشریح باید متن وي.",
            description_max: "تشریح باید له 255 تورو زیاته نه وي.",

        },
        department: {
            tashkil_required: "تشکیل ټاکل اړین دي.",
            tashkil_not_found: "ټاکل شوی تشکیل ونه موندل شو.",
            parent_department_not_found: "اصلي څانګه ونه موندل شوه.",
            name_required: "د څانګې نوم اړین دی.",
            name_invalid: "د څانګې نوم سم نه دی.",
            name_too_long: "د څانګې نوم باید له ۲۵۵ تورو څخه زیات نه وي.",
            name_already_exists: "دا د څانګې نوم مخکې ثبت شوی دی.",
            code_invalid: "د څانګې کوډ سم نه دی.",
            code_too_long: "د څانګې کوډ باید له ۵۰ تورو څخه زیات نه وي.",
            code_already_exists: "دا د څانګې کوډ مخکې ثبت شوی دی.",
            description_invalid: "د څانګې تشریح سمه نه ده.",
        },
        flight_service: {
            flight_required: 'الوتنه اړینه ده.',
            flight_exists: 'ټاکل شوې الوتنه شتون نه لري.',
            service_required: 'د SGHA خدمت ټاکل اړین دي.',
            service_exists: 'ټاکل شوی SGHA خدمت شتون نه لري.',
            count_required: 'تعداد اړین دی.',
            count_integer: 'تعداد باید یو صحیح عدد وي.',
            count_min: 'تعداد باید لږ تر لږه ۱ وي.',
        }

    },
    success: {
        organization_stored_successfully: "اداره په بریالیتوب سره جوړه شوه.",
        organization_updated_successfully: "اداره په بریالیتوب سره تازه شوه.",
        organization_deleted_successfully: "اداره په بریالیتوب سره حذف شوه.",

        department_stored_successfully: "څانګه په بریالیتوب سره جوړه شوه.",
        department_updated_successfully: "څانګه په بریالیتوب سره تازه شوه.",
        department_deleted_successfully: "څانګه په بریالیتوب سره حذف شوه.",

        tashkil_stored_successfully: "تشکیل په بریالیتوب سره جوړ شو.",
        tashkil_updated_successfully: "تشکیل په بریالیتوب سره تازه شو.",
        tashkil_deleted_successfully: "تشکیل په بریالیتوب سره حذف شو.",
    },

    state: {
        approve: "منل",
        disApprove: "ردول",

        active: "فعال",
        blocked: "بند شوی",
        notBlocked: "ندی بند شوی",
        approved: "منل شوی",
        notApproved: "ندی منل شوی ",
        disApproved: "رد شوی",
        deActive: "غیرفعال",
        expired: "موده پای ته رسېدلې",

        activityStatus: "د فعالیت حالت",
        approvalStatus: "د تایید حالت",
    },

    measurement: {
        area: "ساحه",
        meter: "متر",
        kilometer: "کیلومتر",
        squareMeter: "مربع متر",
        hectare: "هکتار",
        kilogram: "کیلوګرام",
        gram: "ګرام",
        liter: "لیتر",
        ton: "ټن",
        foot: "فټ",
        mile: "مایل",
    },

    airport: {
        airportList: "د هواي ډګرونو لیست",
        airport: "هوایي ډګر",
        airports: "هوایي ډګرونه",
        addNewAirport: "نوی هوایي ډګر اضافه کړئ",
        addingNewAirport: "د نوي هوایي دګر اضافه کول",
        airportInfo: "د هوایي ډګر معلومات",
        airportCode: "د هوایي ډګر کوډ",
        runwayLength: "د رنوې اوږدوالی",
        runwayWidth: "د رنوې پلنوالی",
        airportType: " هوایي ډګر ډول",
        aircraftTypes: "د الوتکو ډولونه",
        aircraftType: "د الوتکې ډول",
        addNewAircraftType:"نوی د الوتکې ډول اضافه کړئ",
        addingNewAircraftType:"د الوتکې د نوي ډول اضافه کول",

        aircraftCode: " د الوتکې کوډ",

        type: {
            international: "نړیوال",
            domestic: "کورنی",
            military: "پوځي",
            cargo: "باربري",
            regional: "سیمه‌ییز",
            private: "شخصي",
        },
    },
    airline: {
        airlinesList: "د هوايي شرکتونو لیست",
        addNewAirline: "نوی هوايي شرکت اضافه کړئ",
        addingNewAirline: "د نوي هوايي شرکت اضافه کول",
        airlineInfo: "د هوايي شرکت معلومات",
        airlineCode: "د هوايي شرکت کوډ",
        airlineType: "د هوايي شرکت ډول",
        airline: "هوايي شرکت",
        airlines: "هوايي شرکتونه",
        airlineName: "د هوايي شرکت نوم",
        country: "هیواد",
    },

    flight: {
        flight: "الوتنه",
        flights: "الوتنې",
        flightNumber: "د الوتنې نمبر",
        createFlight: "نوی الوتنه",
        arrival: "رسېدل",
        departureTime: "د روانېدو وخت",
        arrivalTime: "د رسېدو وخت",
        flightServices: "د الوتنو چوپړتیاوې",
        airport: "هوایي ډګر",
        airline: "هوایي شرکت",
        aircraft_type: "د الوتکې ډول",
        aircraft_registration: "د الوتکې ثبت نمبر",
        flight_number: "د پرواز شمېره",
        charge_note: "چارچ نوت",
        arrival_date: "د رسېدو نېټه",
        departure_date: "د وتلو نېټه",
        approximate_time_arrival: "د رسېدو اټکلي وخت",
        approximate_time_departure: "د وتلو اټکلي وخت",
        save_service: "خدمت ثبت کړئ",
        loading: "بارول کیږي...",
        saving: "ثبت کیږي...",
        flightServicesList: "د الوتنو چوپړتیاوې لیست",
        newFlightServices: "نوی چوپړتیاوې",
        searchFlightNumber: "د پرواز شمېره وپلټی",
    },

    sgha: {
        SGHAPart: "د SGHA برخه",
        sghaServiceUnite: "د SGHA خدماتي واحد",
        sghaServices: "د SGHA خدمات",
        sghaServicesList: "د SGHA خدماتو لیست",
        addNewSghaService: "نوی SGHA خدمات اضافه کړئ",
        countOfService: "د خدمات تعداد",
    },

    passenger: {
        passenger: "مسافر",
        passengers: "مسافرین",
        passportNumber: "د پاسپورټ نمبر",
        nationality: "تابعیت",
        gender: "جنس",
        male: "نارینه",
        female: "ښځینه",
    },

    report: {
        reports: "راپورونه",
        dailyReport: "ورځنی راپور",
        monthlyReport: "میاشتنی راپور",
        yearlyReport: "کلنی راپور",
        generateReport: "راپور جوړول",
    },

    user: {
        list: "د کاروونکو لیست",
        users: "کاروونکي",
        addUser: "نوی کاروونکی اضافه کړئ",
        username: "کارن نوم",
        email: "برېښنالیک",
        password: "پټنوم",
        role: "صلاحیت",
        roles: "صلاحیتونه",
        addNewRole: "د نوي صلاحیت زیاتول",

        permissions: "اجازې",
        permissionsList: "د اجازو لیست",
        searchByRoleName: "د صلاحیت په نوم سره لټون وکړئ",
        positionTitle: "د بست عنوان",
        generalDepartment: "عمومي څانګه",

        confirmPassword: "د پټ نوم تایید",
        addingNewUser: "د نوي کاروونکي زیاتول",
        reset: "بیا تنظیمول",

        currentPassword: "اوسنی پټ نوم",
        newPassword: "نوی پټ نوم",
        logout: "له سیستم څخه وتل",
        loggingOut: "له سیستم څخه د وتلو په حال کې",
    },

    construction: {
        constructionsList: "د ودانیو لیست ",
        constructionsTypeList: "د ودانیو د ډولونو لیست ",

        constructionsPart: "د ودانیو برخه",
        buildingsAndFacilities: "ودانۍ او تاسیسات",
        airportConstructions: "د هوايي ډګر ودانۍ/تاسیسات",
        airportConstructionsList: "د هوايي ډګر د ودانیو/تاسیساتو لیست",

        constructions: "ودانۍ",
        constructionsTypes: "د ودانیو ډولونه",

        constructionTypes: "د ودانیو د جوړښت ډولونه",
        constructionCode: "د ودانۍ کوډ",
        newConstruction: "نوې ودانۍ",
        construction: "ودانۍ",
        constructionType: "د ودانۍ ډول",
        addingNewConstruction: "د نوې ودانۍ اضافه کول",
        addNewConstruction: "نوې ودانۍ اضافه کړئ",

        addingNewConstructionType: "د نوی ودانیز جوړښت اضافه کول",
        addNewConstructionType: "نوی ودانیز جوړښت اضافه کړئ",

        constructionTypePashto: "د جوړښت ډول (پښتو)",
        constructionTypeDari: "د جوړښت ډول (دري)",
        constructionTypeEnglish: "د جوړښت ډول (انګلیسی)",
    },

    tashkilat: {
         pleaseAddPositionRequirements: "مهرباني وکړئ د بست اړین شرایط اضافه کړئ",
        selectCertificate: "مهرباني وکړئ اړوند سند انتخاب کړئ",
        selectEducationLevel: "مهرباني وکړئ د زده‌کړې کچه انتخاب کړئ",
        totalRequirments: "د بست د اړینو شرایطو ټوټل",
        selectCourse: "مهرباني وکړئ اړوند کورس انتخاب کړئ",
        validityMonths: "د کورس د اعتبار موده په میاشتو کې",
        courseIsMandatory: "کورس اجباري دی",
        courseIsPrefered: "کورس ترجیحي دی",
        courseIsOptional: "کورس اختیاري دی",
        certificatesPart: "د اسنادو برخه",
        educationPart: "د زده‌کړو برخه",
        trainingsPart: "د کورسونو او روزنو برخه",
        monthOrMonths:"میاشت/ میاشتې",
         Required: "اړین",
  notRequired: " اړین ندی",

        organizations: "اداره عمومی",
        organizationsList: "د ادارو لیست",
        createOrganization: "اداره جوړول",
        tashkil: "تشکیل",
        tashkilatPart: "تشکیلات",
        dashboard: "ډشبورډ",
        departments: "ریاستونه",
        positionTypes: "د بست ډولونه",
        departmentPositions: "د ریاست بستونه",
        employees: "کارکوونکي",
        employeeAssignments: "د کارکوونکو مقررۍ",
        createDepartment: "د څانګې جوړول",
        departmentsList: "د څانګو لست",
        departmentName: "د څانګې نوم",
        parentDepartment: "اصلي څانګه",
        noParent: "اصلي څانګه نشته",
        code: "کوډ",
        tashkilList: "د تشکیلاتو لیست",
        CreateNewTashkil: "نوی تشکیلات جوړول",
        reference_number: "د رییفرنس شمېره",
        year: "کال",
        createNewPositionType: 'د بست ‌‌ډول اضافه کوړی',
        positionType: "د بست ډول",

        createDepartmentPosition: "د ریاست بست جوړول",
        positionTitle: "د بست عنوان",
        department: "ریاست",
        positionTypeList: "د بستونو ډولونه",
        grade: "درجه بست",
        totalPositions: "د بستونو شمېر",
        salary: "معاش",
        description: "تشریح",
        addRequirements: "اړتیاوې اضافه کړئ",
        organization: {
            name: "د ادارې نوم",
            code: "د ادارې کوډ",
            email: "د ادارې برېښنالیک",
            phone: "د ادارې د اړیکې شمېره",
            website: "د ادارې وېب‌پاڼه",
            address: "د ادارې پته",
            create: "اداره جوړول",
        },
        employee: {
            employeeNo: "د کارکوونکي شمېره",
            firstName: "لومړی نوم",
            fullName: "بشپر نوم",
            lastName: "تخلص",
            fatherName: "د پلار نوم",
            gender: "جنسیت",
            birthDate: "د زیږون نېټه",
            phone: "د اړیکې شمېره",
            email: "برېښنالیک",
            nationalId: "د پېژندپاڼې شمېره",
            passportNo: "د پاسپورټ شمېره",
            maritalStatus: "مدني حالت",
            bloodGroup: "د وینې ګروپ",
            province: "ولایت",
            district: "ولسوالي",
            address: "پته",
            photo: "انځور",
            approvalStatus: "د تایید حالت",
            status: "حالت",
            employeeName: "د کارکوونکي نوم",
            employees: "کارکوونکي",
            createEmployee: "د کارکوونکي جوړول",
            employeeList: "د کارکوونکو لېست",
            single: "مجرد",
            married: "واده شوی",
            divorced: "طلاق شوی",
            widowed: "کونډ/کونډه",
            active: "فعال",
            inactive: "غیر فعال"

        },
        employeeAssignment: {
            employeeAssignmentsList: "د کارکوونکو دندو لېست",
            createEmployeeAssignment: "د کارکوونکي دنده جوړول",
            editEmployeeAssignment: "د کارکوونکي دنده سمول",
            employeeName: "د کارکوونکي نوم",
            startDate: "د پیل نېټه",
            endDate: "د پای نېټه",
            approvalStatus: "د تایید حالت",
            selectEmployee: "کارکوونکی وټاکئ",
            selectVacancy: "دنده وټاکئ",
            selectApprovalStatus: "د تایید حالت وټاکئ",
            vacancy: "دنده",
            position: "بست",
            remarks: "نوټونه",
            enterRemarks: "نوټونه دلته ولیکئ...",
            assignmentDetails: "د دندې تفصیلات",
            noAssignmentsFound: "د کارکوونکي دنده ونه موندل شوه",
            assignmentCreated: "د کارکوونکي دنده په بریالیتوب سره جوړه شوه",
            assignmentUpdated: "د کارکوونکي دنده په بریالیتوب سره سمه شوه",
            assignmentDeleted: "د کارکوونکي دنده حذف شوه",
            confirmDelete: "آیا تاسو د دې دندې حذف کولو یقین لرئ؟",
            pending: "په انتظار کې",
            approved: "تایید شوی",
            rejected: "رد شوی",
            underReview: "تر بیاکتنې لاندې"
        },
    },
    education: {
        educationPart: "زده کړی او روزنه",
        educationLevels: "د زده کړې کچې",
        employeeEducation: "د کارکوونکي زده کړې",
        positionRequiredEducation: "د دندې اړینې زده کړې",

        certificates: "سندونه",

        courseTypes: "د کورس ډولونه",
        courses: "کورسونه",



        trainings: "روزنې",
        addNewEducationLevel: "د زده کړې نوې کچه اضافه کړئ",
        educationLevel: "د زده کړې کچه",
        educations: "زده کړې",
        feildofStudy: "څانګه ",
        university: "پوهنتون",
        graduationYear: "د فراغت کال",
        certificate: "سند",
        obtainedDate: "د ترلاسه کولو نېټه",
        expiryDate: "د پای نېټه",
        certificateNumber: "د سند شمېره",
        addCertificate: "سند اضافه کړئ",
        addNewCertificate: "نوی سند اضافه کړئ",
        certificateName: "د سند نوم",
        certificateLevel: "د سند کچه",
        certificateList: "د سندونو لیست",
        createCertificate: "سند جوړول",

        levels: {
            beginner: "لومړنۍ",
            intermediate: "منځنۍ",
            advanced: "پرمختللې",
            expert: "متخصصه",
        },
        courses: {
            courses: "کورسونه",
            courseList: "د کورسونو لیست",
            addNewCourse: "نوی کورس اضافه کړئ",
            addingNewCourse: "د نوي کورس اضافه کول",
            courseInfo: "د کورس معلومات",
            courseCode: "د کورس کوډ",
            courseType: "د کورس ډول",
            courseName: "د کورس نوم",
            validity: "د اعتبار موده (په میاشتو کې)",
            description: "د کورس تشریح",
        },
        trainers: {
            trainers: "روزونکي",
            createTrainer: "نوی روزونکی جوړول",
            editTrainer: "روزونکی سمول",
            id: "پېژندنه",
            name: "بشپړ نوم",
            namePlaceholder: "د روزونکي بشپړ نوم دننه کړئ",
            type: "ډول",
            selectType: "د روزونکي ډول وټاکئ",
            phone: "د تلیفون شمېره",
            phonePlaceholder: "د تلیفون شمېره دننه کړئ",
            email: "برېښناليک",
            emailPlaceholder: "برېښناليک آدرس دننه کړئ",
            licenseNumber: "د جواز شمېره",
            licensePlaceholder: "د جواز شمېره دننه کړئ",
            organization: "اداره/سازمان",
            organizationPlaceholder: "د ادارې نوم دننه کړئ",
            address: "آدرس",
            addressPlaceholder: "آدرس دننه کړئ",
            description: "تشریح",
            descriptionPlaceholder: "تشریح دننه کړئ",
            contact: "اړیکه",
            license: "جواز",
            types: {
                internal: "داخلي",
                external: "بهرنی",
                consultant: "سلاکار"
            }
        },


        trainingPlans: {
            trainingPlans: "د روزنې پلانونه",
            createTrainingPlan: "د روزنې نوی پلان جوړول",
            editTrainingPlan: "د روزنې پلان سمول",
            id: "پېژندنه",
            name: "د پلان نوم",
            namePlaceholder: "د روزنې پلان نوم دننه کړئ",
            course: "کورس",
            selectCourse: "کورس وټاکئ",
            trainer: "روزونکی",
            selectTrainer: "روزونکی وټاکئ",
            startDate: "پیل نیټه",
            endDate: "پای نیټه",
            period: "موده",
            location: "ځای",
            locationPlaceholder: "د روزنې ځای دننه کړئ",
            status: "حالت",
            selectStatus: "حالت وټاکئ",
            description: "تشریح",
            descriptionPlaceholder: "د روزنې پلان تشریح دننه کړئ",
            days: "ورځې",
            statuses: {
                planned: "پلان شوی",
                in_progress: "په روانه توګه",
                completed: "ترسره شوی",
                cancelled: "لغوه شوی"
            }
        },


    }
};

export default pashto;
